<?php

// Data functions (insert, update, delete, form) for table Accounting

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Accounting_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Accounting');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['description'] = $_REQUEST['description'];
		if($data['description'] == empty_lookup_value) { $data['description'] = ''; }
	$data['master_acount'] = $_REQUEST['master_acount'];
		if($data['master_acount'] == empty_lookup_value) { $data['master_acount'] = ''; }
	$data['account'] = $_REQUEST['account'];
		if($data['account'] == empty_lookup_value) { $data['account'] = ''; }
	$data['sub_account'] = $_REQUEST['sub_account'];
		if($data['sub_account'] == empty_lookup_value) { $data['sub_account'] = ''; }
	$data['type'] = $_REQUEST['type'];
		if($data['type'] == empty_lookup_value) { $data['type'] = ''; }
	$data['amount'] = $_REQUEST['amount'];
		if($data['amount'] == empty_lookup_value) { $data['amount'] = ''; }

	// hook: Accounting_before_insert
	if(function_exists('Accounting_before_insert')) {
		$args = array();
		if(!Accounting_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Accounting', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Accounting_after_insert
	if(function_exists('Accounting_after_insert')) {
		$res = sql("select * from `Accounting` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Accounting_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Accounting', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Accounting_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Accounting_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Accounting_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Accounting');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Accounting' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Accounting' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Accounting_before_delete
	if(function_exists('Accounting_before_delete')) {
		$args=array();
		if(!Accounting_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Accounting` where `id`='$selected_id'", $eo);

	// hook: Accounting_after_delete
	if(function_exists('Accounting_after_delete')) {
		$args=array();
		Accounting_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Accounting' and pkValue='$selected_id'", $eo);
}

function Accounting_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Accounting');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Accounting' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Accounting' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['description'] = makeSafe($_REQUEST['description']);
		if($data['description'] == empty_lookup_value) { $data['description'] = ''; }
	$data['master_acount'] = makeSafe($_REQUEST['master_acount']);
		if($data['master_acount'] == empty_lookup_value) { $data['master_acount'] = ''; }
	$data['account'] = makeSafe($_REQUEST['account']);
		if($data['account'] == empty_lookup_value) { $data['account'] = ''; }
	$data['sub_account'] = makeSafe($_REQUEST['sub_account']);
		if($data['sub_account'] == empty_lookup_value) { $data['sub_account'] = ''; }
	$data['type'] = makeSafe($_REQUEST['type']);
		if($data['type'] == empty_lookup_value) { $data['type'] = ''; }
	$data['amount'] = makeSafe($_REQUEST['amount']);
		if($data['amount'] == empty_lookup_value) { $data['amount'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Accounting_before_update
	if(function_exists('Accounting_before_update')) {
		$args = array();
		if(!Accounting_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Accounting` set       `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `master_acount`=' . (($data['master_acount'] !== '' && $data['master_acount'] !== NULL) ? "'{$data['master_acount']}'" : 'NULL') . ', `account`=' . (($data['account'] !== '' && $data['account'] !== NULL) ? "'{$data['account']}'" : 'NULL') . ', `sub_account`=' . (($data['sub_account'] !== '' && $data['sub_account'] !== NULL) ? "'{$data['sub_account']}'" : 'NULL') . ', `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL') . ', `amount`=' . (($data['amount'] !== '' && $data['amount'] !== NULL) ? "'{$data['amount']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Accounting_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Accounting_after_update
	if(function_exists('Accounting_after_update')) {
		$res = sql("SELECT * FROM `Accounting` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Accounting_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Accounting' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Accounting_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Accounting');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_master_acount = thisOr(undo_magic_quotes($_REQUEST['filterer_master_acount']), '');
	$filterer_account = thisOr(undo_magic_quotes($_REQUEST['filterer_account']), '');
	$filterer_sub_account = thisOr(undo_magic_quotes($_REQUEST['filterer_sub_account']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_account && !$filterer_master_acount) $filterer_master_acount = sqlValue("select masterAccount from Account where id='" . makeSafe($filterer_account) . "'");
	if($filterer_sub_account && !$filterer_account) $filterer_account = sqlValue("select account from SubAccount where id='" . makeSafe($filterer_sub_account) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: master_acount
	$combo_master_acount = new DataCombo;
	// combobox: account, filterable by: master_acount
	$combo_account = new DataCombo;
	// combobox: sub_account, filterable by: account
	$combo_sub_account = new DataCombo;
	// combobox: type
	$combo_type = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Accounting' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Accounting' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Accounting` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Accounting_view.php', false);
		}
		$combo_date->DefaultDate = $row['date'];
		$combo_master_acount->SelectedData = $row['master_acount'];
		$combo_account->SelectedData = $row['account'];
		$combo_sub_account->SelectedData = $row['sub_account'];
		$combo_type->SelectedData = $row['type'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_master_acount->SelectedData = $filterer_master_acount;
		$combo_account->SelectedData = $filterer_account;
		$combo_sub_account->SelectedData = $filterer_sub_account;
		$combo_type->SelectedData = $filterer_type;
	}
	$combo_master_acount->HTML = '<span id="master_acount-container' . $rnd1 . '"></span><input type="hidden" name="master_acount" id="master_acount' . $rnd1 . '" value="' . html_attr($combo_master_acount->SelectedData) . '">';
	$combo_master_acount->MatchText = '<span id="master_acount-container-readonly' . $rnd1 . '"></span><input type="hidden" name="master_acount" id="master_acount' . $rnd1 . '" value="' . html_attr($combo_master_acount->SelectedData) . '">';
	$combo_account->HTML = '<span id="account-container' . $rnd1 . '"></span><input type="hidden" name="account" id="account' . $rnd1 . '" value="' . html_attr($combo_account->SelectedData) . '">';
	$combo_account->MatchText = '<span id="account-container-readonly' . $rnd1 . '"></span><input type="hidden" name="account" id="account' . $rnd1 . '" value="' . html_attr($combo_account->SelectedData) . '">';
	$combo_sub_account->HTML = '<span id="sub_account-container' . $rnd1 . '"></span><input type="hidden" name="sub_account" id="sub_account' . $rnd1 . '" value="' . html_attr($combo_sub_account->SelectedData) . '">';
	$combo_sub_account->MatchText = '<span id="sub_account-container-readonly' . $rnd1 . '"></span><input type="hidden" name="sub_account" id="sub_account' . $rnd1 . '" value="' . html_attr($combo_sub_account->SelectedData) . '">';
	$combo_type->HTML = '<span id="type-container' . $rnd1 . '"></span><input type="hidden" name="type" id="type' . $rnd1 . '" value="' . html_attr($combo_type->SelectedData) . '">';
	$combo_type->MatchText = '<span id="type-container-readonly' . $rnd1 . '"></span><input type="hidden" name="type" id="type' . $rnd1 . '" value="' . html_attr($combo_type->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_master_acount__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['master_acount'] : $filterer_master_acount); ?>"};
		AppGini.current_account__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['account'] : $filterer_account); ?>"};
		AppGini.current_sub_account__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['sub_account'] : $filterer_sub_account); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(master_acount_reload__RAND__) == 'function') master_acount_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(account_reload__RAND__) == \'function\') account_reload__RAND__(AppGini.current_master_acount__RAND__.value);' : ''); ?>
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(sub_account_reload__RAND__) == \'function\') sub_account_reload__RAND__(AppGini.current_account__RAND__.value);' : ''); ?>
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function master_acount_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#master_acount-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_master_acount__RAND__.value, t: 'Accounting', f: 'master_acount' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="master_acount"]').val(resp.results[0].id);
							$j('[id=master_acount-container-readonly__RAND__]').html('<span id="master_acount-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=MasterAccount_view_parent]').hide(); }else{ $j('.btn[id=MasterAccount_view_parent]').show(); }

						if(typeof(account_reload__RAND__) == 'function') account_reload__RAND__(AppGini.current_master_acount__RAND__.value);

							if(typeof(master_acount_update_autofills__RAND__) == 'function') master_acount_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Accounting', f: 'master_acount' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_master_acount__RAND__.value = e.added.id;
				AppGini.current_master_acount__RAND__.text = e.added.text;
				$j('[name="master_acount"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=MasterAccount_view_parent]').hide(); }else{ $j('.btn[id=MasterAccount_view_parent]').show(); }

						if(typeof(account_reload__RAND__) == 'function') account_reload__RAND__(AppGini.current_master_acount__RAND__.value);

				if(typeof(master_acount_update_autofills__RAND__) == 'function') master_acount_update_autofills__RAND__();
			});

			if(!$j("#master_acount-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_master_acount__RAND__.value, t: 'Accounting', f: 'master_acount' },
					success: function(resp) {
						$j('[name="master_acount"]').val(resp.results[0].id);
						$j('[id=master_acount-container-readonly__RAND__]').html('<span id="master_acount-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=MasterAccount_view_parent]').hide(); }else{ $j('.btn[id=MasterAccount_view_parent]').show(); }

						if(typeof(master_acount_update_autofills__RAND__) == 'function') master_acount_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_master_acount__RAND__.value, t: 'Accounting', f: 'master_acount' },
				success: function(resp) {
					$j('[id=master_acount-container__RAND__], [id=master_acount-container-readonly__RAND__]').html('<span id="master_acount-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=MasterAccount_view_parent]').hide(); }else{ $j('.btn[id=MasterAccount_view_parent]').show(); }

					if(typeof(master_acount_update_autofills__RAND__) == 'function') master_acount_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function account_reload__RAND__(filterer_master_acount) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#account-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_master_acount: filterer_master_acount, id: AppGini.current_account__RAND__.value, t: 'Accounting', f: 'account' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="account"]').val(resp.results[0].id);
							$j('[id=account-container-readonly__RAND__]').html('<span id="account-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Account_view_parent]').hide(); }else{ $j('.btn[id=Account_view_parent]').show(); }

						if(typeof(sub_account_reload__RAND__) == 'function') sub_account_reload__RAND__(AppGini.current_account__RAND__.value);

							if(typeof(account_update_autofills__RAND__) == 'function') account_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { filterer_master_acount: filterer_master_acount, s: term, p: page, t: 'Accounting', f: 'account' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_account__RAND__.value = e.added.id;
				AppGini.current_account__RAND__.text = e.added.text;
				$j('[name="account"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Account_view_parent]').hide(); }else{ $j('.btn[id=Account_view_parent]').show(); }

						if(typeof(sub_account_reload__RAND__) == 'function') sub_account_reload__RAND__(AppGini.current_account__RAND__.value);

				if(typeof(account_update_autofills__RAND__) == 'function') account_update_autofills__RAND__();
			});

			if(!$j("#account-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_account__RAND__.value, t: 'Accounting', f: 'account' },
					success: function(resp) {
						$j('[name="account"]').val(resp.results[0].id);
						$j('[id=account-container-readonly__RAND__]').html('<span id="account-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Account_view_parent]').hide(); }else{ $j('.btn[id=Account_view_parent]').show(); }

						if(typeof(account_update_autofills__RAND__) == 'function') account_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_account__RAND__.value, t: 'Accounting', f: 'account' },
				success: function(resp) {
					$j('[id=account-container__RAND__], [id=account-container-readonly__RAND__]').html('<span id="account-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Account_view_parent]').hide(); }else{ $j('.btn[id=Account_view_parent]').show(); }

					if(typeof(account_update_autofills__RAND__) == 'function') account_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function sub_account_reload__RAND__(filterer_account) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#sub_account-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_account: filterer_account, id: AppGini.current_sub_account__RAND__.value, t: 'Accounting', f: 'sub_account' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="sub_account"]').val(resp.results[0].id);
							$j('[id=sub_account-container-readonly__RAND__]').html('<span id="sub_account-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=SubAccount_view_parent]').hide(); }else{ $j('.btn[id=SubAccount_view_parent]').show(); }


							if(typeof(sub_account_update_autofills__RAND__) == 'function') sub_account_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { filterer_account: filterer_account, s: term, p: page, t: 'Accounting', f: 'sub_account' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_sub_account__RAND__.value = e.added.id;
				AppGini.current_sub_account__RAND__.text = e.added.text;
				$j('[name="sub_account"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=SubAccount_view_parent]').hide(); }else{ $j('.btn[id=SubAccount_view_parent]').show(); }


				if(typeof(sub_account_update_autofills__RAND__) == 'function') sub_account_update_autofills__RAND__();
			});

			if(!$j("#sub_account-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_sub_account__RAND__.value, t: 'Accounting', f: 'sub_account' },
					success: function(resp) {
						$j('[name="sub_account"]').val(resp.results[0].id);
						$j('[id=sub_account-container-readonly__RAND__]').html('<span id="sub_account-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=SubAccount_view_parent]').hide(); }else{ $j('.btn[id=SubAccount_view_parent]').show(); }

						if(typeof(sub_account_update_autofills__RAND__) == 'function') sub_account_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_sub_account__RAND__.value, t: 'Accounting', f: 'sub_account' },
				success: function(resp) {
					$j('[id=sub_account-container__RAND__], [id=sub_account-container-readonly__RAND__]').html('<span id="sub_account-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=SubAccount_view_parent]').hide(); }else{ $j('.btn[id=SubAccount_view_parent]').show(); }

					if(typeof(sub_account_update_autofills__RAND__) == 'function') sub_account_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Accounting_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Accounting_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'ALL details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Accounting_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Accounting_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Accounting_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#master_acount').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#master_acount_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#account').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#account_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#sub_account').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#sub_account_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#type').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#amount').replaceWith('<div class=\"form-control-static\" id=\"amount\">' + (jQuery('#amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(master_acount)%%>', $combo_master_acount->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(master_acount)%%>', $combo_master_acount->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(master_acount)%%>', urlencode($combo_master_acount->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(account)%%>', $combo_account->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(account)%%>', $combo_account->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(account)%%>', urlencode($combo_account->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(sub_account)%%>', $combo_sub_account->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(sub_account)%%>', $combo_sub_account->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(sub_account)%%>', urlencode($combo_sub_account->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(type)%%>', $combo_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(type)%%>', $combo_type->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(type)%%>', urlencode($combo_type->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('master_acount' => array('MasterAccount', 'Master account'), 'account' => array('Account', 'Account'), 'sub_account' => array('SubAccount', 'Subaccount'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(master_acount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(account)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sub_account)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(balance)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5">' . html_attr($row['description']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<div id="description" class="form-control-static">' . $row['description'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(description)%%>', nl2br($row['description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(master_acount)%%>', safe_html($urow['master_acount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(master_acount)%%>', html_attr($row['master_acount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(master_acount)%%>', urlencode($urow['master_acount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(account)%%>', safe_html($urow['account']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(account)%%>', html_attr($row['account']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(account)%%>', urlencode($urow['account']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sub_account)%%>', safe_html($urow['sub_account']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sub_account)%%>', html_attr($row['sub_account']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sub_account)%%>', urlencode($urow['sub_account']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', safe_html($urow['type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', html_attr($row['type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', safe_html($urow['amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', html_attr($row['amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode($urow['amount']), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance)%%>', safe_html($urow['balance']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance)%%>', urlencode($urow['balance']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(master_acount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(master_acount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(account)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(account)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sub_account)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sub_account)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Accounting');
	if($selected_id) {
		$jdata = get_joined_record('Accounting', $selected_id);
		if($jdata === false) $jdata = get_defaults('Accounting');
		$rdata = $row;
	}
	$templateCode .= loadView('Accounting-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Accounting_dv
	if(function_exists('Accounting_dv')) {
		$args=array();
		Accounting_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>