<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/AccountPlan.php");
	include("$currDir/AccountPlan_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('AccountPlan');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "AccountPlan";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`AccountPlan`.`id`" => "id",
		"`AccountPlan`.`description`" => "description",
		"`AccountPlan`.`code`" => "code",
		"IF(    CHAR_LENGTH(`MasterAccount1`.`masterAccount`) || CHAR_LENGTH(`MasterAccount1`.`code`), CONCAT_WS('',   `MasterAccount1`.`masterAccount`, ' - ', `MasterAccount1`.`code`), '') /* Master account */" => "master_account",
		"IF(    CHAR_LENGTH(`Account1`.`Account`) || CHAR_LENGTH(`Account1`.`code`), CONCAT_WS('',   `Account1`.`Account`, ' - ', `Account1`.`code`), '') /* Account */" => "account",
		"IF(    CHAR_LENGTH(`SubAccount1`.`subAccount`) || CHAR_LENGTH(`SubAccount1`.`code`), CONCAT_WS('',   `SubAccount1`.`subAccount`, ' - ', `SubAccount1`.`code`), '') /* Sub account */" => "sub_account",
		"IF(    CHAR_LENGTH(`Type1`.`type`), CONCAT_WS('',   `Type1`.`type`), '') /* Type */" => "type",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`AccountPlan`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`Type1`.`type`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`AccountPlan`.`id`" => "id",
		"`AccountPlan`.`description`" => "description",
		"`AccountPlan`.`code`" => "code",
		"IF(    CHAR_LENGTH(`MasterAccount1`.`masterAccount`) || CHAR_LENGTH(`MasterAccount1`.`code`), CONCAT_WS('',   `MasterAccount1`.`masterAccount`, ' - ', `MasterAccount1`.`code`), '') /* Master account */" => "master_account",
		"IF(    CHAR_LENGTH(`Account1`.`Account`) || CHAR_LENGTH(`Account1`.`code`), CONCAT_WS('',   `Account1`.`Account`, ' - ', `Account1`.`code`), '') /* Account */" => "account",
		"IF(    CHAR_LENGTH(`SubAccount1`.`subAccount`) || CHAR_LENGTH(`SubAccount1`.`code`), CONCAT_WS('',   `SubAccount1`.`subAccount`, ' - ', `SubAccount1`.`code`), '') /* Sub account */" => "sub_account",
		"IF(    CHAR_LENGTH(`Type1`.`type`), CONCAT_WS('',   `Type1`.`type`), '') /* Type */" => "type",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`AccountPlan`.`id`" => "ID",
		"`AccountPlan`.`description`" => "Description",
		"`AccountPlan`.`code`" => "Code",
		"IF(    CHAR_LENGTH(`MasterAccount1`.`masterAccount`) || CHAR_LENGTH(`MasterAccount1`.`code`), CONCAT_WS('',   `MasterAccount1`.`masterAccount`, ' - ', `MasterAccount1`.`code`), '') /* Master account */" => "Master account",
		"IF(    CHAR_LENGTH(`Account1`.`Account`) || CHAR_LENGTH(`Account1`.`code`), CONCAT_WS('',   `Account1`.`Account`, ' - ', `Account1`.`code`), '') /* Account */" => "Account",
		"IF(    CHAR_LENGTH(`SubAccount1`.`subAccount`) || CHAR_LENGTH(`SubAccount1`.`code`), CONCAT_WS('',   `SubAccount1`.`subAccount`, ' - ', `SubAccount1`.`code`), '') /* Sub account */" => "Sub account",
		"IF(    CHAR_LENGTH(`Type1`.`type`), CONCAT_WS('',   `Type1`.`type`), '') /* Type */" => "Type",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`AccountPlan`.`id`" => "id",
		"`AccountPlan`.`description`" => "description",
		"`AccountPlan`.`code`" => "code",
		"IF(    CHAR_LENGTH(`MasterAccount1`.`masterAccount`) || CHAR_LENGTH(`MasterAccount1`.`code`), CONCAT_WS('',   `MasterAccount1`.`masterAccount`, ' - ', `MasterAccount1`.`code`), '') /* Master account */" => "master_account",
		"IF(    CHAR_LENGTH(`Account1`.`Account`) || CHAR_LENGTH(`Account1`.`code`), CONCAT_WS('',   `Account1`.`Account`, ' - ', `Account1`.`code`), '') /* Account */" => "account",
		"IF(    CHAR_LENGTH(`SubAccount1`.`subAccount`) || CHAR_LENGTH(`SubAccount1`.`code`), CONCAT_WS('',   `SubAccount1`.`subAccount`, ' - ', `SubAccount1`.`code`), '') /* Sub account */" => "sub_account",
		"IF(    CHAR_LENGTH(`Type1`.`type`), CONCAT_WS('',   `Type1`.`type`), '') /* Type */" => "type",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('master_account' => 'Master account', 'account' => 'Account', 'sub_account' => 'Sub account', 'type' => 'Type', );

	$x->QueryFrom = "`AccountPlan` LEFT JOIN `MasterAccount` as MasterAccount1 ON `MasterAccount1`.`id`=`AccountPlan`.`master_account` LEFT JOIN `Account` as Account1 ON `Account1`.`id`=`AccountPlan`.`account` LEFT JOIN `SubAccount` as SubAccount1 ON `SubAccount1`.`id`=`AccountPlan`.`sub_account` LEFT JOIN `Type` as Type1 ON `Type1`.`id`=`AccountPlan`.`type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "AccountPlan_view.php";
	$x->RedirectAfterInsert = "AccountPlan_view.php?SelectedID=#ID#";
	$x->TableTitle = "Account Plan";
	$x->TableIcon = "resources/table_icons/chart_curve.png";
	$x->PrimaryKey = "`AccountPlan`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Description", "Code", "Master account", "Account", "Sub account", "Type");
	$x->ColFieldName = array('description', 'code', 'master_account', 'account', 'sub_account', 'type');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/AccountPlan_templateTV.html';
	$x->SelectedTemplate = 'templates/AccountPlan_templateTVS.html';
	$x->TemplateDV = 'templates/AccountPlan_templateDV.html';
	$x->TemplateDVP = 'templates/AccountPlan_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `AccountPlan`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='AccountPlan' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `AccountPlan`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='AccountPlan' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`AccountPlan`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: AccountPlan_init
	$render=TRUE;
	if(function_exists('AccountPlan_init')) {
		$args=array();
		$render=AccountPlan_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: AccountPlan_header
	$headerCode='';
	if(function_exists('AccountPlan_header')) {
		$args=array();
		$headerCode=AccountPlan_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: AccountPlan_footer
	$footerCode='';
	if(function_exists('AccountPlan_footer')) {
		$args=array();
		$footerCode=AccountPlan_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>