<?php

// Data functions (insert, update, delete, form) for table Activities

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Activities_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Activities');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Date'] = intval($_REQUEST['DateYear']) . '-' . intval($_REQUEST['DateMonth']) . '-' . intval($_REQUEST['DateDay']);
	$data['Date'] = parseMySQLDate($data['Date'], '1');
	$data['Description'] = $_REQUEST['Description'];
		if($data['Description'] == empty_lookup_value) { $data['Description'] = ''; }
	$data['Comment'] = br2nl($_REQUEST['Comment']);
	$data['Priority'] = $_REQUEST['Priority'];
		if($data['Priority'] == empty_lookup_value) { $data['Priority'] = ''; }
	$data['Assigned'] = $_REQUEST['Assigned'];
		if($data['Assigned'] == empty_lookup_value) { $data['Assigned'] = ''; }
	$data['Completed'] = $_REQUEST['Completed'];
		if($data['Completed'] == empty_lookup_value) { $data['Completed'] = ''; }
	$data['Stop'] = mysql_datetime($_REQUEST['Stop']);
		if($data['Stop'] == empty_lookup_value) { $data['Stop'] = ''; }

	// hook: Activities_before_insert
	if(function_exists('Activities_before_insert')) {
		$args = array();
		if(!Activities_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Activities', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Activities_after_insert
	if(function_exists('Activities_after_insert')) {
		$res = sql("select * from `Activities` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Activities_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Activities', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Activities_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Activities_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Activities_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Activities');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Activities' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Activities' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Activities_before_delete
	if(function_exists('Activities_before_delete')) {
		$args=array();
		if(!Activities_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Activities` where `id`='$selected_id'", $eo);

	// hook: Activities_after_delete
	if(function_exists('Activities_after_delete')) {
		$args=array();
		Activities_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Activities' and pkValue='$selected_id'", $eo);
}

function Activities_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Activities');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Activities' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Activities' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Date'] = intval($_REQUEST['DateYear']) . '-' . intval($_REQUEST['DateMonth']) . '-' . intval($_REQUEST['DateDay']);
	$data['Date'] = parseMySQLDate($data['Date'], '1');
	$data['Description'] = makeSafe($_REQUEST['Description']);
		if($data['Description'] == empty_lookup_value) { $data['Description'] = ''; }
	$data['Comment'] = br2nl(makeSafe($_REQUEST['Comment']));
	$data['Priority'] = makeSafe($_REQUEST['Priority']);
		if($data['Priority'] == empty_lookup_value) { $data['Priority'] = ''; }
	$data['Assigned'] = makeSafe($_REQUEST['Assigned']);
		if($data['Assigned'] == empty_lookup_value) { $data['Assigned'] = ''; }
	$data['Completed'] = makeSafe($_REQUEST['Completed']);
		if($data['Completed'] == empty_lookup_value) { $data['Completed'] = ''; }
	$data['Stop'] = mysql_datetime($_REQUEST['Stop']);
		if($data['Stop'] == empty_lookup_value) { $data['Stop'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Activities_before_update
	if(function_exists('Activities_before_update')) {
		$args = array();
		if(!Activities_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Activities` set       `Date`=' . (($data['Date'] !== '' && $data['Date'] !== NULL) ? "'{$data['Date']}'" : 'NULL') . ', `Description`=' . (($data['Description'] !== '' && $data['Description'] !== NULL) ? "'{$data['Description']}'" : 'NULL') . ', `Comment`=' . (($data['Comment'] !== '' && $data['Comment'] !== NULL) ? "'{$data['Comment']}'" : 'NULL') . ', `Priority`=' . (($data['Priority'] !== '' && $data['Priority'] !== NULL) ? "'{$data['Priority']}'" : 'NULL') . ', `Assigned`=' . (($data['Assigned'] !== '' && $data['Assigned'] !== NULL) ? "'{$data['Assigned']}'" : 'NULL') . ', `Completed`=' . (($data['Completed'] !== '' && $data['Completed'] !== NULL) ? "'{$data['Completed']}'" : 'NULL') . ', `Stop`=' . (($data['Stop'] !== '' && $data['Stop'] !== NULL) ? "'{$data['Stop']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Activities_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Activities_after_update
	if(function_exists('Activities_after_update')) {
		$res = sql("SELECT * FROM `Activities` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Activities_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Activities' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Activities_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Activities');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Assigned = thisOr(undo_magic_quotes($_REQUEST['filterer_Assigned']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Date
	$combo_Date = new DateCombo;
	$combo_Date->DateFormat = "mdy";
	$combo_Date->MinYear = 1900;
	$combo_Date->MaxYear = 2100;
	$combo_Date->DefaultDate = parseMySQLDate('1', '1');
	$combo_Date->MonthNames = $Translation['month names'];
	$combo_Date->NamePrefix = 'Date';
	// combobox: Priority
	$combo_Priority = new Combo;
	$combo_Priority->ListType = 0;
	$combo_Priority->MultipleSeparator = ', ';
	$combo_Priority->ListBoxHeight = 10;
	$combo_Priority->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Activities.Priority.csv')) {
		$Priority_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Activities.Priority.csv')));
		$combo_Priority->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Priority_data)));
		$combo_Priority->ListData = $combo_Priority->ListItem;
	}else{
		$combo_Priority->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Priority 1;;Priority 2;;Priority 3;;Urgent;;")));
		$combo_Priority->ListData = $combo_Priority->ListItem;
	}
	$combo_Priority->SelectName = 'Priority';
	// combobox: Assigned
	$combo_Assigned = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Activities' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Activities' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Activities` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Activities_view.php', false);
		}
		$combo_Date->DefaultDate = $row['Date'];
		$combo_Priority->SelectedData = $row['Priority'];
		$combo_Assigned->SelectedData = $row['Assigned'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_Priority->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_Assigned->SelectedData = $filterer_Assigned;
	}
	$combo_Priority->Render();
	$combo_Assigned->HTML = '<span id="Assigned-container' . $rnd1 . '"></span><input type="hidden" name="Assigned" id="Assigned' . $rnd1 . '" value="' . html_attr($combo_Assigned->SelectedData) . '">';
	$combo_Assigned->MatchText = '<span id="Assigned-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Assigned" id="Assigned' . $rnd1 . '" value="' . html_attr($combo_Assigned->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Assigned__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Assigned'] : $filterer_Assigned); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Assigned_reload__RAND__) == 'function') Assigned_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Assigned_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Assigned-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Assigned__RAND__.value, t: 'Activities', f: 'Assigned' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Assigned"]').val(resp.results[0].id);
							$j('[id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


							if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Activities', f: 'Assigned' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Assigned__RAND__.value = e.added.id;
				AppGini.current_Assigned__RAND__.text = e.added.text;
				$j('[name="Assigned"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


				if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
			});

			if(!$j("#Assigned-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Assigned__RAND__.value, t: 'Activities', f: 'Assigned' },
					success: function(resp) {
						$j('[name="Assigned"]').val(resp.results[0].id);
						$j('[id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

						if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Assigned__RAND__.value, t: 'Activities', f: 'Assigned' },
				success: function(resp) {
					$j('[id=Assigned-container__RAND__], [id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

					if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Activities_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Activities_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Activitie details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Activities_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Activities_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Activities_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DateDay, #DateMonth, #DateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Comment').replaceWith('<div class=\"form-control-static\" id=\"Comment\">' + (jQuery('#Comment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Priority').replaceWith('<div class=\"form-control-static\" id=\"Priority\">' + (jQuery('#Priority').val() || '') + '</div>'); jQuery('#Priority-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Assigned').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Assigned_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Completed').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Stop').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Stop\">' + (jQuery('#Stop').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Stop').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Date->GetHTML(true) . '</div>' : $combo_Date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Date)%%>', $combo_Date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Priority)%%>', $combo_Priority->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Priority)%%>', $combo_Priority->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Assigned)%%>', $combo_Assigned->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Assigned)%%>', $combo_Assigned->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Assigned)%%>', urlencode($combo_Assigned->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Assigned' => array('Staff', 'Assigned'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Comment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Priority)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assigned)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Completed)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Stop)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', @date('m/d/Y', @strtotime(html_attr($row['Date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Date'])))), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5">' . html_attr($row['Description']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<div id="Description" class="form-control-static">' . $row['Description'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Description)%%>', nl2br($row['Description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode($urow['Description']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Comment)%%>', safe_html($urow['Comment']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(Comment)%%>', html_attr($row['Comment']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Comment)%%>', urlencode($urow['Comment']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Priority)%%>', safe_html($urow['Priority']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Priority)%%>', html_attr($row['Priority']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Priority)%%>', urlencode($urow['Priority']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Assigned)%%>', safe_html($urow['Assigned']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Assigned)%%>', html_attr($row['Assigned']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned)%%>', urlencode($urow['Assigned']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Completed)%%>', ($row['Completed'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%VALUE(Stop)%%>', app_datetime($row['Stop'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Stop)%%>', urlencode(app_datetime($urow['Stop'], 'dt')), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(Comment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Comment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Priority)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Priority)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Completed)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(Stop)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Stop)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Activities');
	if($selected_id) {
		$jdata = get_joined_record('Activities', $selected_id);
		if($jdata === false) $jdata = get_defaults('Activities');
		$rdata = $row;
	}
	$templateCode .= loadView('Activities-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Activities_dv
	if(function_exists('Activities_dv')) {
		$args=array();
		Activities_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>