<?php

// Data functions (insert, update, delete, form) for table Alert

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Alert_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Alert');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Customer'] = $_REQUEST['Customer'];
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	$data['Satus'] = $_REQUEST['Satus'];
		if($data['Satus'] == empty_lookup_value) { $data['Satus'] = ''; }
	$data['Comment'] = $_REQUEST['Comment'];
		if($data['Comment'] == empty_lookup_value) { $data['Comment'] = ''; }
	$data['Date'] = parseCode('<%%creationDateTime%%>', true, true);

	// hook: Alert_before_insert
	if(function_exists('Alert_before_insert')) {
		$args = array();
		if(!Alert_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Alert', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Alert_after_insert
	if(function_exists('Alert_after_insert')) {
		$res = sql("select * from `Alert` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Alert_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Alert', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Alert_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Alert_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Alert_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Alert');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Alert' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Alert' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Alert_before_delete
	if(function_exists('Alert_before_delete')) {
		$args=array();
		if(!Alert_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Alert` where `id`='$selected_id'", $eo);

	// hook: Alert_after_delete
	if(function_exists('Alert_after_delete')) {
		$args=array();
		Alert_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Alert' and pkValue='$selected_id'", $eo);
}

function Alert_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Alert');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Alert' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Alert' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Customer'] = makeSafe($_REQUEST['Customer']);
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	$data['Satus'] = makeSafe($_REQUEST['Satus']);
		if($data['Satus'] == empty_lookup_value) { $data['Satus'] = ''; }
	$data['Comment'] = makeSafe($_REQUEST['Comment']);
		if($data['Comment'] == empty_lookup_value) { $data['Comment'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Alert_before_update
	if(function_exists('Alert_before_update')) {
		$args = array();
		if(!Alert_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Alert` set       `Customer`=' . (($data['Customer'] !== '' && $data['Customer'] !== NULL) ? "'{$data['Customer']}'" : 'NULL') . ', `Satus`=' . (($data['Satus'] !== '' && $data['Satus'] !== NULL) ? "'{$data['Satus']}'" : 'NULL') . ', `Comment`=' . (($data['Comment'] !== '' && $data['Comment'] !== NULL) ? "'{$data['Comment']}'" : 'NULL') . ', `Date`=`Date`' . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Alert_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Alert_after_update
	if(function_exists('Alert_after_update')) {
		$res = sql("SELECT * FROM `Alert` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Alert_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Alert' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Alert_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Alert');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Customer = thisOr(undo_magic_quotes($_REQUEST['filterer_Customer']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Customer
	$combo_Customer = new DataCombo;
	// combobox: Satus
	$combo_Satus = new Combo;
	$combo_Satus->ListType = 0;
	$combo_Satus->MultipleSeparator = ', ';
	$combo_Satus->ListBoxHeight = 10;
	$combo_Satus->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Alert.Satus.csv')) {
		$Satus_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Alert.Satus.csv')));
		$combo_Satus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Satus_data)));
		$combo_Satus->ListData = $combo_Satus->ListItem;
	}else{
		$combo_Satus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("WARNING;;RISK CONTROLLED;;CONTROLLED")));
		$combo_Satus->ListData = $combo_Satus->ListItem;
	}
	$combo_Satus->SelectName = 'Satus';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Alert' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Alert' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Alert` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Alert_view.php', false);
		}
		$combo_Customer->SelectedData = $row['Customer'];
		$combo_Satus->SelectedData = $row['Satus'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_Customer->SelectedData = $filterer_Customer;
		$combo_Satus->SelectedText = ( $_REQUEST['FilterField'][1]=='3' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_Customer->HTML = '<span id="Customer-container' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_Customer->MatchText = '<span id="Customer-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_Satus->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Customer__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Customer'] : $filterer_Customer); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Customer_reload__RAND__) == 'function') Customer_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Customer_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Customer-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Customer__RAND__.value, t: 'Alert', f: 'Customer' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Customer"]').val(resp.results[0].id);
							$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


							if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Alert', f: 'Customer' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Customer__RAND__.value = e.added.id;
				AppGini.current_Customer__RAND__.text = e.added.text;
				$j('[name="Customer"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


				if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
			});

			if(!$j("#Customer-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Customer__RAND__.value, t: 'Alert', f: 'Customer' },
					success: function(resp) {
						$j('[name="Customer"]').val(resp.results[0].id);
						$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

						if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Customer__RAND__.value, t: 'Alert', f: 'Customer' },
				success: function(resp) {
					$j('[id=Customer-container__RAND__], [id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

					if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Alert_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Alert_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Alert details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Alert_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Alert_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Alert_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Customer').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Customer_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Satus').replaceWith('<div class=\"form-control-static\" id=\"Satus\">' + (jQuery('#Satus').val() || '') + '</div>'); jQuery('#Satus-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Comment').replaceWith('<div class=\"form-control-static\" id=\"Comment\">' + (jQuery('#Comment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Customer)%%>', $combo_Customer->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Customer)%%>', $combo_Customer->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Customer)%%>', urlencode($combo_Customer->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Satus)%%>', $combo_Satus->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Satus)%%>', $combo_Satus->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Customer' => array('Customers', 'Customer'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Customer)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Satus)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Comment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', safe_html($urow['Customer']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', html_attr($row['Customer']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode($urow['Customer']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Satus)%%>', safe_html($urow['Satus']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Satus)%%>', html_attr($row['Satus']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Satus)%%>', urlencode($urow['Satus']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Comment)%%>', safe_html($urow['Comment']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Comment)%%>', html_attr($row['Comment']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Comment)%%>', urlencode($urow['Comment']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', app_datetime($row['Date'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode(app_datetime($urow['Date'], 'dt')), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Customer)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Satus)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Satus)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Comment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Comment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Alert');
	if($selected_id) {
		$jdata = get_joined_record('Alert', $selected_id);
		if($jdata === false) $jdata = get_defaults('Alert');
		$rdata = $row;
	}
	$templateCode .= loadView('Alert-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Alert_dv
	if(function_exists('Alert_dv')) {
		$args=array();
		Alert_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>