<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Claim.php");
	include("$currDir/Claim_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Claim');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Claim";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Claim`.`id`" => "id",
		"if(`Claim`.`Date`,date_format(`Claim`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"`Claim`.`Invoice`" => "Invoice",
		"IF(    CHAR_LENGTH(`Warehouse1`.`Warehouse`), CONCAT_WS('',   `Warehouse1`.`Warehouse`), '') /* Warehouse */" => "Warehouse",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`Claim`.`Selecteds`" => "Selecteds",
		"`Claim`.`Shippingt`" => "Shippingt",
		"`Claim`.`Status`" => "Status",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Claim`.`id`',
		2 => '`Claim`.`Date`',
		3 => 3,
		4 => '`Warehouse1`.`Warehouse`',
		5 => '`Tracking1`.`Tracking`',
		6 => 6,
		7 => 7,
		8 => 8,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Claim`.`id`" => "id",
		"if(`Claim`.`Date`,date_format(`Claim`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"`Claim`.`Invoice`" => "Invoice",
		"IF(    CHAR_LENGTH(`Warehouse1`.`Warehouse`), CONCAT_WS('',   `Warehouse1`.`Warehouse`), '') /* Warehouse */" => "Warehouse",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`Claim`.`Selecteds`" => "Selecteds",
		"`Claim`.`Shippingt`" => "Shippingt",
		"`Claim`.`Status`" => "Status",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Claim`.`id`" => "ID",
		"`Claim`.`Date`" => "Date",
		"`Claim`.`Invoice`" => "Invoice",
		"IF(    CHAR_LENGTH(`Warehouse1`.`Warehouse`), CONCAT_WS('',   `Warehouse1`.`Warehouse`), '') /* Warehouse */" => "Warehouse",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`Claim`.`Selecteds`" => "Required Shipment",
		"`Claim`.`Shippingt`" => "Shipping type",
		"`Claim`.`Status`" => "Status",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Claim`.`id`" => "id",
		"if(`Claim`.`Date`,date_format(`Claim`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"`Claim`.`Invoice`" => "Invoice",
		"IF(    CHAR_LENGTH(`Warehouse1`.`Warehouse`), CONCAT_WS('',   `Warehouse1`.`Warehouse`), '') /* Warehouse */" => "Warehouse",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`Claim`.`Selecteds`" => "Selecteds",
		"`Claim`.`Shippingt`" => "Shippingt",
		"`Claim`.`Status`" => "Status",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('Warehouse' => 'Warehouse', 'Tracking' => 'Tracking', );

	$x->QueryFrom = "`Claim` LEFT JOIN `Warehouse` as Warehouse1 ON `Warehouse1`.`id`=`Claim`.`Warehouse` LEFT JOIN `Tracking` as Tracking1 ON `Tracking1`.`id`=`Claim`.`Tracking` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 300;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Claim_view.php";
	$x->RedirectAfterInsert = "Claim_view.php?SelectedID=#ID#";
	$x->TableTitle = "CLAIM";
	$x->TableIcon = "resources/table_icons/Claim.png";
	$x->PrimaryKey = "`Claim`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Date", "Invoice", "Warehouse", "Tracking", "Required Shipment", "Shipping type", "Status");
	$x->ColFieldName = array('Date', 'Invoice', 'Warehouse', 'Tracking', 'Selecteds', 'Shippingt', 'Status');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Claim_templateTV.html';
	$x->SelectedTemplate = 'templates/Claim_templateTVS.html';
	$x->TemplateDV = 'templates/Claim_templateDV.html';
	$x->TemplateDVP = 'templates/Claim_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Claim`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Claim' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Claim`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Claim' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Claim`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Claim_init
	$render=TRUE;
	if(function_exists('Claim_init')) {
		$args=array();
		$render=Claim_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Claim_header
	$headerCode='';
	if(function_exists('Claim_header')) {
		$args=array();
		$headerCode=Claim_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Claim_footer
	$footerCode='';
	if(function_exists('Claim_footer')) {
		$args=array();
		$footerCode=Claim_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>