<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Customers.php");
	include("$currDir/Customers_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Customers');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Customers";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Customers`.`id`" => "id",
		"`Customers`.`Title`" => "Title",
		"`Customers`.`Customer`" => "Customer",
		"if(`Customers`.`Birthdate`,date_format(`Customers`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"IF(    CHAR_LENGTH(`CustomerClass1`.`Type`), CONCAT_WS('',   `CustomerClass1`.`Type`), '') /* Type */" => "Type",
		"`Customers`.`Phone`" => "Phone",
		"`Customers`.`Email`" => "Email",
		"`Customers`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"`Customers`.`Status`" => "Status",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Customers`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Customers`.`Birthdate`',
		5 => '`CustomerClass1`.`Type`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`City1`.`City`',
		10 => '`Province1`.`Province`',
		11 => '`Country1`.`Country`',
		12 => 12,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Customers`.`id`" => "id",
		"`Customers`.`Title`" => "Title",
		"`Customers`.`Customer`" => "Customer",
		"if(`Customers`.`Birthdate`,date_format(`Customers`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"IF(    CHAR_LENGTH(`CustomerClass1`.`Type`), CONCAT_WS('',   `CustomerClass1`.`Type`), '') /* Type */" => "Type",
		"`Customers`.`Phone`" => "Phone",
		"`Customers`.`Email`" => "Email",
		"`Customers`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"`Customers`.`Status`" => "Status",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Customers`.`id`" => "ID",
		"`Customers`.`Title`" => "Title",
		"`Customers`.`Customer`" => "Customer",
		"`Customers`.`Birthdate`" => "Birthdate",
		"IF(    CHAR_LENGTH(`CustomerClass1`.`Type`), CONCAT_WS('',   `CustomerClass1`.`Type`), '') /* Type */" => "Type",
		"`Customers`.`Phone`" => "Phone",
		"`Customers`.`Email`" => "Email",
		"`Customers`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"`Customers`.`Status`" => "Status",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Customers`.`id`" => "id",
		"`Customers`.`Title`" => "Title",
		"`Customers`.`Customer`" => "Customer",
		"if(`Customers`.`Birthdate`,date_format(`Customers`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"IF(    CHAR_LENGTH(`CustomerClass1`.`Type`), CONCAT_WS('',   `CustomerClass1`.`Type`), '') /* Type */" => "Type",
		"`Customers`.`Phone`" => "Phone",
		"`Customers`.`Email`" => "Email",
		"`Customers`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"`Customers`.`Status`" => "Status",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('Type' => 'Type', 'City' => 'City', 'Province' => 'Province', 'Country' => 'Country', );

	$x->QueryFrom = "`Customers` LEFT JOIN `CustomerClass` as CustomerClass1 ON `CustomerClass1`.`id`=`Customers`.`Type` LEFT JOIN `City` as City1 ON `City1`.`id`=`Customers`.`City` LEFT JOIN `Province` as Province1 ON `Province1`.`id`=`Customers`.`Province` LEFT JOIN `Country` as Country1 ON `Country1`.`id`=`Customers`.`Country` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 300;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Customers_view.php";
	$x->RedirectAfterInsert = "Customers_view.php?SelectedID=#ID#";
	$x->TableTitle = "CUSTOMERS";
	$x->TableIcon = "resources/table_icons/Customers.png";
	$x->PrimaryKey = "`Customers`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Title", "Customer", "Birthdate", "Type", "Phone", "Email", "Address", "Status");
	$x->ColFieldName = array('Title', 'Customer', 'Birthdate', 'Type', 'Phone', 'Email', 'Address', 'Status');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Customers_templateTV.html';
	$x->SelectedTemplate = 'templates/Customers_templateTVS.html';
	$x->TemplateDV = 'templates/Customers_templateDV.html';
	$x->TemplateDVP = 'templates/Customers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Customers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Customers' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Customers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Customers' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Customers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Customers_init
	$render=TRUE;
	if(function_exists('Customers_init')) {
		$args=array();
		$render=Customers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Customers_header
	$headerCode='';
	if(function_exists('Customers_header')) {
		$args=array();
		$headerCode=Customers_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Customers_footer
	$footerCode='';
	if(function_exists('Customers_footer')) {
		$args=array();
		$footerCode=Customers_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>