<?php

// Data functions (insert, update, delete, form) for table Invoice

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Invoice_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Invoice');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['type'] = $_REQUEST['type'];
		if($data['type'] == empty_lookup_value) { $data['type'] = ''; }
	$data['number'] = $_REQUEST['number'];
		if($data['number'] == empty_lookup_value) { $data['number'] = ''; }
	$data['Date'] = intval($_REQUEST['DateYear']) . '-' . intval($_REQUEST['DateMonth']) . '-' . intval($_REQUEST['DateDay']);
	$data['Date'] = parseMySQLDate($data['Date'], '1');
	$data['Title'] = $_REQUEST['Customer'];
		if($data['Title'] == empty_lookup_value) { $data['Title'] = ''; }
	$data['Customer'] = $_REQUEST['Customer'];
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	$data['Phone'] = $_REQUEST['Customer'];
		if($data['Phone'] == empty_lookup_value) { $data['Phone'] = ''; }
	$data['Email'] = $_REQUEST['Customer'];
		if($data['Email'] == empty_lookup_value) { $data['Email'] = ''; }
	$data['Address'] = $_REQUEST['Customer'];
		if($data['Address'] == empty_lookup_value) { $data['Address'] = ''; }
	$data['City'] = $_REQUEST['Customer'];
		if($data['City'] == empty_lookup_value) { $data['City'] = ''; }
	$data['Country'] = $_REQUEST['Customer'];
		if($data['Country'] == empty_lookup_value) { $data['Country'] = ''; }
	$data['PaymentStatus'] = $_REQUEST['PaymentStatus'];
		if($data['PaymentStatus'] == empty_lookup_value) { $data['PaymentStatus'] = ''; }
	$data['Status'] = $_REQUEST['Status'];
		if($data['Status'] == empty_lookup_value) { $data['Status'] = ''; }
	$data['tax'] = $_REQUEST['tax'];
		if($data['tax'] == empty_lookup_value) { $data['tax'] = ''; }
	$data['usrAdd'] = parseCode('<%%creatorUsername%%>', true);
	$data['whenAdd'] = parseCode('<%%creationDateTime%%>', true);
	if($data['type'] == '') $data['type'] = "Quote";
	if($data['number']== '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Number': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['Customer']== '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Customer': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['PaymentStatus'] == '') $data['PaymentStatus'] = "UNPAID";
	if($data['Status'] == '') $data['Status'] = "OPEN";

	// hook: Invoice_before_insert
	if(function_exists('Invoice_before_insert')) {
		$args = array();
		if(!Invoice_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Invoice', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// automatic related if passed as filterer
	if($_REQUEST['filterer_related']) {
		sql("update `Invoice` set `related`='" . makeSafe($_REQUEST['filterer_related']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: Invoice_after_insert
	if(function_exists('Invoice_after_insert')) {
		$res = sql("select * from `Invoice` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Invoice_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Invoice', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Invoice_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Invoice_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// copy InvoiceDetails
	$res = sql("SELECT * FROM `InvoiceDetails` WHERE `invoice`='{$safe_sid}'", $eo);
	while($row = db_fetch_assoc($res)) {
		$data = array(
			'SelectedID' => $row['id'],
			'invoice' => $destination_id,
			'order' => $row['order'],
			'product' => $row['product'],
			'qty' => $row['qty'],
			'itemSale' => $row['itemSale'],
		);

		$ch = curl_insert_handler('InvoiceDetails', $data);
		if($ch !== false) $requests[] = $ch;
	}

	// launch requests, asynchronously
	curl_batch($requests);
}

function Invoice_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Invoice');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Invoice' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Invoice' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Invoice_before_delete
	if(function_exists('Invoice_before_delete')) {
		$args=array();
		if(!Invoice_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Status
	$res = sql("select `id` from `Invoice` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `Status` where `Invoice`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Status", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Status", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: Invoice
	$res = sql("select `id` from `Invoice` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `Invoice` where `related`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Invoice", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Invoice", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: InvoiceDetails
	$res = sql("select `id` from `Invoice` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `InvoiceDetails` where `invoice`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "InvoiceDetails", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "InvoiceDetails", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: Accounting
	$res = sql("select `id` from `Invoice` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `Accounting` where `invoice`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Accounting", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Accounting", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Invoice_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `Invoice` where `id`='$selected_id'", $eo);

	// hook: Invoice_after_delete
	if(function_exists('Invoice_after_delete')) {
		$args=array();
		Invoice_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Invoice' and pkValue='$selected_id'", $eo);
}

function Invoice_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Invoice');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Invoice' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Invoice' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['type'] = makeSafe($_REQUEST['type']);
		if($data['type'] == empty_lookup_value) { $data['type'] = ''; }
	$data['number'] = makeSafe($_REQUEST['number']);
		if($data['number'] == empty_lookup_value) { $data['number'] = ''; }
	if($data['number']=='') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Number': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Date'] = intval($_REQUEST['DateYear']) . '-' . intval($_REQUEST['DateMonth']) . '-' . intval($_REQUEST['DateDay']);
	$data['Date'] = parseMySQLDate($data['Date'], '1');
	$data['Title'] = makeSafe($_REQUEST['Customer']);
		if($data['Title'] == empty_lookup_value) { $data['Title'] = ''; }
	$data['Customer'] = makeSafe($_REQUEST['Customer']);
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	if($data['Customer']=='') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Customer': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Phone'] = makeSafe($_REQUEST['Customer']);
		if($data['Phone'] == empty_lookup_value) { $data['Phone'] = ''; }
	$data['Email'] = makeSafe($_REQUEST['Customer']);
		if($data['Email'] == empty_lookup_value) { $data['Email'] = ''; }
	$data['Address'] = makeSafe($_REQUEST['Customer']);
		if($data['Address'] == empty_lookup_value) { $data['Address'] = ''; }
	$data['City'] = makeSafe($_REQUEST['Customer']);
		if($data['City'] == empty_lookup_value) { $data['City'] = ''; }
	$data['Country'] = makeSafe($_REQUEST['Customer']);
		if($data['Country'] == empty_lookup_value) { $data['Country'] = ''; }
	$data['PaymentStatus'] = makeSafe($_REQUEST['PaymentStatus']);
		if($data['PaymentStatus'] == empty_lookup_value) { $data['PaymentStatus'] = ''; }
	$data['Status'] = makeSafe($_REQUEST['Status']);
		if($data['Status'] == empty_lookup_value) { $data['Status'] = ''; }
	$data['tax'] = makeSafe($_REQUEST['tax']);
		if($data['tax'] == empty_lookup_value) { $data['tax'] = ''; }
	$data['usrUpdated'] = parseCode('<%%editorUsername%%>', false);
	$data['whenUpdated'] = parseCode('<%%editingDateTime%%>', false);
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Invoice_before_update
	if(function_exists('Invoice_before_update')) {
		$args = array();
		if(!Invoice_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Invoice` set       `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL') . ', `number`=' . (($data['number'] !== '' && $data['number'] !== NULL) ? "'{$data['number']}'" : 'NULL') . ', `Date`=' . (($data['Date'] !== '' && $data['Date'] !== NULL) ? "'{$data['Date']}'" : 'NULL') . ', `Title`=' . (($data['Title'] !== '' && $data['Title'] !== NULL) ? "'{$data['Title']}'" : 'NULL') . ', `Customer`=' . (($data['Customer'] !== '' && $data['Customer'] !== NULL) ? "'{$data['Customer']}'" : 'NULL') . ', `Phone`=' . (($data['Phone'] !== '' && $data['Phone'] !== NULL) ? "'{$data['Phone']}'" : 'NULL') . ', `Email`=' . (($data['Email'] !== '' && $data['Email'] !== NULL) ? "'{$data['Email']}'" : 'NULL') . ', `Address`=' . (($data['Address'] !== '' && $data['Address'] !== NULL) ? "'{$data['Address']}'" : 'NULL') . ', `City`=' . (($data['City'] !== '' && $data['City'] !== NULL) ? "'{$data['City']}'" : 'NULL') . ', `Country`=' . (($data['Country'] !== '' && $data['Country'] !== NULL) ? "'{$data['Country']}'" : 'NULL') . ', `PaymentStatus`=' . (($data['PaymentStatus'] !== '' && $data['PaymentStatus'] !== NULL) ? "'{$data['PaymentStatus']}'" : 'NULL') . ', `Status`=' . (($data['Status'] !== '' && $data['Status'] !== NULL) ? "'{$data['Status']}'" : 'NULL') . ', `tax`=' . (($data['tax'] !== '' && $data['tax'] !== NULL) ? "'{$data['tax']}'" : 'NULL') . ', `whenAdd`=`whenAdd`' . ', `usrUpdated`=' . "'{$data['usrUpdated']}'" . ', `whenUpdated`=' . "'{$data['whenUpdated']}'" . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Invoice_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Invoice_after_update
	if(function_exists('Invoice_after_update')) {
		$res = sql("SELECT * FROM `Invoice` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Invoice_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Invoice' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Invoice_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Invoice');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Customer = thisOr(undo_magic_quotes($_REQUEST['filterer_Customer']), '');
	$filterer_related = thisOr(undo_magic_quotes($_REQUEST['filterer_related']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: type
	$combo_type = new Combo;
	$combo_type->ListType = 0;
	$combo_type->MultipleSeparator = ', ';
	$combo_type->ListBoxHeight = 10;
	$combo_type->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Invoice.type.csv')) {
		$type_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Invoice.type.csv')));
		$combo_type->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($type_data)));
		$combo_type->ListData = $combo_type->ListItem;
	}else{
		$combo_type->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Quote;;Invoice")));
		$combo_type->ListData = $combo_type->ListItem;
	}
	$combo_type->SelectName = 'type';
	// combobox: Date
	$combo_Date = new DateCombo;
	$combo_Date->DateFormat = "mdy";
	$combo_Date->MinYear = 1900;
	$combo_Date->MaxYear = 2100;
	$combo_Date->DefaultDate = parseMySQLDate('1', '1');
	$combo_Date->MonthNames = $Translation['month names'];
	$combo_Date->NamePrefix = 'Date';
	// combobox: Customer
	$combo_Customer = new DataCombo;
	// combobox: PaymentStatus
	$combo_PaymentStatus = new Combo;
	$combo_PaymentStatus->ListType = 0;
	$combo_PaymentStatus->MultipleSeparator = ', ';
	$combo_PaymentStatus->ListBoxHeight = 10;
	$combo_PaymentStatus->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Invoice.PaymentStatus.csv')) {
		$PaymentStatus_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Invoice.PaymentStatus.csv')));
		$combo_PaymentStatus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($PaymentStatus_data)));
		$combo_PaymentStatus->ListData = $combo_PaymentStatus->ListItem;
	}else{
		$combo_PaymentStatus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("UNPAID;;PARTIAL PAYMENT;;PAID")));
		$combo_PaymentStatus->ListData = $combo_PaymentStatus->ListItem;
	}
	$combo_PaymentStatus->SelectName = 'PaymentStatus';
	// combobox: Status
	$combo_Status = new Combo;
	$combo_Status->ListType = 0;
	$combo_Status->MultipleSeparator = ', ';
	$combo_Status->ListBoxHeight = 10;
	$combo_Status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Invoice.Status.csv')) {
		$Status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Invoice.Status.csv')));
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Status_data)));
		$combo_Status->ListData = $combo_Status->ListItem;
	}else{
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("OPEN;;CLOSED;;CANCELED")));
		$combo_Status->ListData = $combo_Status->ListItem;
	}
	$combo_Status->SelectName = 'Status';
	// combobox: related
	$combo_related = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Invoice' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Invoice' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Invoice` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Invoice_view.php', false);
		}
		$combo_type->SelectedData = $row['type'];
		$combo_Date->DefaultDate = $row['Date'];
		$combo_Customer->SelectedData = $row['Customer'];
		$combo_PaymentStatus->SelectedData = $row['PaymentStatus'];
		$combo_Status->SelectedData = $row['Status'];
		$combo_related->SelectedData = $row['related'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_type->SelectedText = ( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "Quote");
		$combo_Customer->SelectedData = $filterer_Customer;
		$combo_PaymentStatus->SelectedText = ( $_REQUEST['FilterField'][1]=='12' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "UNPAID");
		$combo_Status->SelectedText = ( $_REQUEST['FilterField'][1]=='16' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "OPEN");
		$combo_related->SelectedData = $filterer_related;
	}
	$combo_type->Render();
	$combo_Customer->HTML = '<span id="Customer-container' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_Customer->MatchText = '<span id="Customer-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_PaymentStatus->Render();
	$combo_Status->Render();
	$combo_related->HTML = '<span id="related-container' . $rnd1 . '"></span><input type="hidden" name="related" id="related' . $rnd1 . '" value="' . html_attr($combo_related->SelectedData) . '">';
	$combo_related->MatchText = '<span id="related-container-readonly' . $rnd1 . '"></span><input type="hidden" name="related" id="related' . $rnd1 . '" value="' . html_attr($combo_related->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Customer__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Customer'] : $filterer_Customer); ?>"};
		AppGini.current_related__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['related'] : $filterer_related); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Customer_reload__RAND__) == 'function') Customer_reload__RAND__();
				if(typeof(related_reload__RAND__) == 'function') related_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Customer_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Customer-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Customer__RAND__.value, t: 'Invoice', f: 'Customer' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Customer"]').val(resp.results[0].id);
							$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


							if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Invoice', f: 'Customer' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Customer__RAND__.value = e.added.id;
				AppGini.current_Customer__RAND__.text = e.added.text;
				$j('[name="Customer"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


				if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
			});

			if(!$j("#Customer-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Customer__RAND__.value, t: 'Invoice', f: 'Customer' },
					success: function(resp) {
						$j('[name="Customer"]').val(resp.results[0].id);
						$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

						if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Customer__RAND__.value, t: 'Invoice', f: 'Customer' },
				success: function(resp) {
					$j('[id=Customer-container__RAND__], [id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

					if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function related_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#related-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_related__RAND__.value, t: 'Invoice', f: 'related' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="related"]').val(resp.results[0].id);
							$j('[id=related-container-readonly__RAND__]').html('<span id="related-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Invoice_view_parent]').hide(); }else{ $j('.btn[id=Invoice_view_parent]').show(); }


							if(typeof(related_update_autofills__RAND__) == 'function') related_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Invoice', f: 'related' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_related__RAND__.value = e.added.id;
				AppGini.current_related__RAND__.text = e.added.text;
				$j('[name="related"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Invoice_view_parent]').hide(); }else{ $j('.btn[id=Invoice_view_parent]').show(); }


				if(typeof(related_update_autofills__RAND__) == 'function') related_update_autofills__RAND__();
			});

			if(!$j("#related-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_related__RAND__.value, t: 'Invoice', f: 'related' },
					success: function(resp) {
						$j('[name="related"]').val(resp.results[0].id);
						$j('[id=related-container-readonly__RAND__]').html('<span id="related-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Invoice_view_parent]').hide(); }else{ $j('.btn[id=Invoice_view_parent]').show(); }

						if(typeof(related_update_autofills__RAND__) == 'function') related_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_related__RAND__.value, t: 'Invoice', f: 'related' },
				success: function(resp) {
					$j('[id=related-container__RAND__], [id=related-container-readonly__RAND__]').html('<span id="related-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Invoice_view_parent]').hide(); }else{ $j('.btn[id=Invoice_view_parent]').show(); }

					if(typeof(related_update_autofills__RAND__) == 'function') related_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Invoice_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Invoice_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Invoice details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Invoice_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Invoice_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Invoice_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#type').replaceWith('<div class=\"form-control-static\" id=\"type\">' + (jQuery('#type').val() || '') + '</div>'); jQuery('#type-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#number').replaceWith('<div class=\"form-control-static\" id=\"number\">' + (jQuery('#number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DateDay, #DateMonth, #DateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Customer').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Customer_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Email, #Email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#PaymentStatus').replaceWith('<div class=\"form-control-static\" id=\"PaymentStatus\">' + (jQuery('#PaymentStatus').val() || '') + '</div>'); jQuery('#PaymentStatus-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Status').replaceWith('<div class=\"form-control-static\" id=\"Status\">' + (jQuery('#Status').val() || '') + '</div>'); jQuery('#Status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#tax').replaceWith('<div class=\"form-control-static\" id=\"tax\">' + (jQuery('#tax').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(type)%%>', $combo_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(type)%%>', $combo_type->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Date->GetHTML(true) . '</div>' : $combo_Date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Date)%%>', $combo_Date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Customer)%%>', $combo_Customer->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Customer)%%>', $combo_Customer->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Customer)%%>', urlencode($combo_Customer->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(PaymentStatus)%%>', $combo_PaymentStatus->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(PaymentStatus)%%>', $combo_PaymentStatus->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Status)%%>', $combo_Status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Status)%%>', $combo_Status->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(related)%%>', $combo_related->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(related)%%>', $combo_related->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(related)%%>', urlencode($combo_related->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Customer' => array('Customers', 'Customer'), 'related' => array('Invoice', 'Related'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Customer)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PaymentStatus)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(AmountDUE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(AmountPAID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Balance)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tax)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Total)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(usrAdd)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whenAdd)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(usrUpdated)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whenUpdated)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(related)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', safe_html($urow['type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', html_attr($row['type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(number)%%>', safe_html($urow['number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(number)%%>', html_attr($row['number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(number)%%>', urlencode($urow['number']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', @date('m/d/Y', @strtotime(html_attr($row['Date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', safe_html($urow['Customer']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', html_attr($row['Customer']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode($urow['Customer']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PaymentStatus)%%>', safe_html($urow['PaymentStatus']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PaymentStatus)%%>', html_attr($row['PaymentStatus']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PaymentStatus)%%>', urlencode($urow['PaymentStatus']), $templateCode);
		$templateCode = str_replace('<%%VALUE(AmountDUE)%%>', safe_html($urow['AmountDUE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AmountDUE)%%>', urlencode($urow['AmountDUE']), $templateCode);
		$templateCode = str_replace('<%%VALUE(AmountPAID)%%>', safe_html($urow['AmountPAID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AmountPAID)%%>', urlencode($urow['AmountPAID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Balance)%%>', safe_html($urow['Balance']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Balance)%%>', urlencode($urow['Balance']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', safe_html($urow['Status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', html_attr($row['Status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode($urow['Status']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tax)%%>', safe_html($urow['tax']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tax)%%>', html_attr($row['tax']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tax)%%>', urlencode($urow['tax']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Total)%%>', safe_html($urow['Total']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Total)%%>', urlencode($urow['Total']), $templateCode);
		$templateCode = str_replace('<%%VALUE(usrAdd)%%>', safe_html($urow['usrAdd']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usrAdd)%%>', urlencode($urow['usrAdd']), $templateCode);
		$templateCode = str_replace('<%%VALUE(whenAdd)%%>', safe_html($urow['whenAdd']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whenAdd)%%>', urlencode($urow['whenAdd']), $templateCode);
		$templateCode = str_replace('<%%VALUE(usrUpdated)%%>', safe_html($urow['usrUpdated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usrUpdated)%%>', urlencode($urow['usrUpdated']), $templateCode);
		$templateCode = str_replace('<%%VALUE(whenUpdated)%%>', safe_html($urow['whenUpdated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whenUpdated)%%>', urlencode($urow['whenUpdated']), $templateCode);
		$templateCode = str_replace('<%%VALUE(related)%%>', safe_html($urow['related']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(related)%%>', urlencode($urow['related']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(type)%%>', 'Quote', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode('Quote'), $templateCode);
		$templateCode = str_replace('<%%VALUE(number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Customer)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PaymentStatus)%%>', 'UNPAID', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PaymentStatus)%%>', urlencode('UNPAID'), $templateCode);
		$templateCode = str_replace('<%%VALUE(AmountDUE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AmountDUE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(AmountPAID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AmountPAID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Balance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Balance)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Status)%%>', 'OPEN', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode('OPEN'), $templateCode);
		$templateCode = str_replace('<%%VALUE(tax)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tax)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Total)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Total)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(usrAdd)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usrAdd)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(whenAdd)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whenAdd)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(usrUpdated)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(usrUpdated)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(whenUpdated)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whenUpdated)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(related)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(related)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('EmailEdit')) { document.getElementById('EmailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('EmailEditLink')) { document.getElementById('EmailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tCustomer_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Invoice_autofill.php?rnd1=$rnd1&mfk=Customer&id=' + encodeURIComponent('".addslashes($row['Customer'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Invoice_autofill.php?rnd1=$rnd1&mfk=Customer&id=' + encodeURIComponent(AppGini.current_Customer{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Customer$rnd1').prop('disabled', true); \$j('#CustomerLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#Customer$rnd1').prop('disabled', false); " : "\$j('#Customer$rnd1').prop('disabled', true); ")."\$j('#CustomerLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Customer_caption').length) \$j('#Customer_caption').click(function() { /* */ Customer_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='23' && $_REQUEST['FilterOperator'][1]=='<=>') {
		$templateCode.="\n<input type=hidden name=related value=\"" . html_attr((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Invoice');
	if($selected_id) {
		$jdata = get_joined_record('Invoice', $selected_id);
		if($jdata === false) $jdata = get_defaults('Invoice');
		$rdata = $row;
	}
	$templateCode .= loadView('Invoice-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Invoice_dv
	if(function_exists('Invoice_dv')) {
		$args=array();
		Invoice_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>