<?php

// Data functions (insert, update, delete, form) for table Payroll

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Payroll_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Payroll');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['employee'] = $_REQUEST['employee'];
		if($data['employee'] == empty_lookup_value) { $data['employee'] = ''; }
	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['start'] = parseCode('<%%creationTime%%>', true);
	$data['horas'] = $_REQUEST['horas'];
		if($data['horas'] == empty_lookup_value) { $data['horas'] = ''; }
	$data['comment'] = $_REQUEST['comment'];
		if($data['comment'] == empty_lookup_value) { $data['comment'] = ''; }
	$data['value'] = $_REQUEST['value'];
		if($data['value'] == empty_lookup_value) { $data['value'] = ''; }
	$data['status'] = $_REQUEST['status'];
		if($data['status'] == empty_lookup_value) { $data['status'] = ''; }
	if($data['status'] == '') $data['status'] = "UNPAID";

	// hook: Payroll_before_insert
	if(function_exists('Payroll_before_insert')) {
		$args = array();
		if(!Payroll_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Payroll', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Payroll_after_insert
	if(function_exists('Payroll_after_insert')) {
		$res = sql("select * from `Payroll` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Payroll_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Payroll', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Payroll_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Payroll_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Payroll_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Payroll');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Payroll' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Payroll' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Payroll_before_delete
	if(function_exists('Payroll_before_delete')) {
		$args=array();
		if(!Payroll_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Payroll` where `id`='$selected_id'", $eo);

	// hook: Payroll_after_delete
	if(function_exists('Payroll_after_delete')) {
		$args=array();
		Payroll_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Payroll' and pkValue='$selected_id'", $eo);
}

function Payroll_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Payroll');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Payroll' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Payroll' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['employee'] = makeSafe($_REQUEST['employee']);
		if($data['employee'] == empty_lookup_value) { $data['employee'] = ''; }
	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['stop'] = parseCode('<%%editingTime%%>', false);
	$data['horas'] = makeSafe($_REQUEST['horas']);
		if($data['horas'] == empty_lookup_value) { $data['horas'] = ''; }
	$data['comment'] = makeSafe($_REQUEST['comment']);
		if($data['comment'] == empty_lookup_value) { $data['comment'] = ''; }
	$data['value'] = makeSafe($_REQUEST['value']);
		if($data['value'] == empty_lookup_value) { $data['value'] = ''; }
	$data['status'] = makeSafe($_REQUEST['status']);
		if($data['status'] == empty_lookup_value) { $data['status'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Payroll_before_update
	if(function_exists('Payroll_before_update')) {
		$args = array();
		if(!Payroll_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Payroll` set       `employee`=' . (($data['employee'] !== '' && $data['employee'] !== NULL) ? "'{$data['employee']}'" : 'NULL') . ', `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `start`=`start`' . ', `stop`=' . "'{$data['stop']}'" . ', `horas`=' . (($data['horas'] !== '' && $data['horas'] !== NULL) ? "'{$data['horas']}'" : 'NULL') . ', `comment`=' . (($data['comment'] !== '' && $data['comment'] !== NULL) ? "'{$data['comment']}'" : 'NULL') . ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Payroll_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Payroll_after_update
	if(function_exists('Payroll_after_update')) {
		$res = sql("SELECT * FROM `Payroll` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Payroll_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Payroll' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Payroll_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Payroll');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_employee = thisOr(undo_magic_quotes($_REQUEST['filterer_employee']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: employee
	$combo_employee = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: status
	$combo_status = new Combo;
	$combo_status->ListType = 0;
	$combo_status->MultipleSeparator = ', ';
	$combo_status->ListBoxHeight = 10;
	$combo_status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Payroll.status.csv')) {
		$status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Payroll.status.csv')));
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($status_data)));
		$combo_status->ListData = $combo_status->ListItem;
	}else{
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("PAID;;UNPAID;;CANCEL")));
		$combo_status->ListData = $combo_status->ListItem;
	}
	$combo_status->SelectName = 'status';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Payroll' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Payroll' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Payroll` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Payroll_view.php', false);
		}
		$combo_employee->SelectedData = $row['employee'];
		$combo_date->DefaultDate = $row['date'];
		$combo_status->SelectedData = $row['status'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_employee->SelectedData = $filterer_employee;
		$combo_status->SelectedText = ( $_REQUEST['FilterField'][1]=='9' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "UNPAID");
	}
	$combo_employee->HTML = '<span id="employee-container' . $rnd1 . '"></span><input type="hidden" name="employee" id="employee' . $rnd1 . '" value="' . html_attr($combo_employee->SelectedData) . '">';
	$combo_employee->MatchText = '<span id="employee-container-readonly' . $rnd1 . '"></span><input type="hidden" name="employee" id="employee' . $rnd1 . '" value="' . html_attr($combo_employee->SelectedData) . '">';
	$combo_status->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_employee__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['employee'] : $filterer_employee); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(employee_reload__RAND__) == 'function') employee_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function employee_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#employee-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_employee__RAND__.value, t: 'Payroll', f: 'employee' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="employee"]').val(resp.results[0].id);
							$j('[id=employee-container-readonly__RAND__]').html('<span id="employee-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


							if(typeof(employee_update_autofills__RAND__) == 'function') employee_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Payroll', f: 'employee' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_employee__RAND__.value = e.added.id;
				AppGini.current_employee__RAND__.text = e.added.text;
				$j('[name="employee"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


				if(typeof(employee_update_autofills__RAND__) == 'function') employee_update_autofills__RAND__();
			});

			if(!$j("#employee-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_employee__RAND__.value, t: 'Payroll', f: 'employee' },
					success: function(resp) {
						$j('[name="employee"]').val(resp.results[0].id);
						$j('[id=employee-container-readonly__RAND__]').html('<span id="employee-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

						if(typeof(employee_update_autofills__RAND__) == 'function') employee_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_employee__RAND__.value, t: 'Payroll', f: 'employee' },
				success: function(resp) {
					$j('[id=employee-container__RAND__], [id=employee-container-readonly__RAND__]').html('<span id="employee-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

					if(typeof(employee_update_autofills__RAND__) == 'function') employee_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Payroll_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Payroll_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Payroll details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Payroll_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Payroll_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Payroll_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#employee').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#employee_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#horas').replaceWith('<div class=\"form-control-static\" id=\"horas\">' + (jQuery('#horas').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#comment').replaceWith('<div class=\"form-control-static\" id=\"comment\">' + (jQuery('#comment').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#status').replaceWith('<div class=\"form-control-static\" id=\"status\">' + (jQuery('#status').val() || '') + '</div>'); jQuery('#status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(employee)%%>', $combo_employee->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(employee)%%>', $combo_employee->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(employee)%%>', urlencode($combo_employee->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(status)%%>', $combo_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(status)%%>', $combo_status->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('employee' => array('Staff', 'Employee'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(employee)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(start)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(stop)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(horas)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comment)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(value)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(employee)%%>', safe_html($urow['employee']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(employee)%%>', html_attr($row['employee']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(employee)%%>', urlencode($urow['employee']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(start)%%>', safe_html($urow['start']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(start)%%>', urlencode($urow['start']), $templateCode);
		$templateCode = str_replace('<%%VALUE(stop)%%>', safe_html($urow['stop']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(stop)%%>', urlencode($urow['stop']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(horas)%%>', safe_html($urow['horas']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(horas)%%>', html_attr($row['horas']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(horas)%%>', urlencode($urow['horas']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(comment)%%>', safe_html($urow['comment']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(comment)%%>', html_attr($row['comment']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comment)%%>', urlencode($urow['comment']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(value)%%>', safe_html($urow['value']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(value)%%>', html_attr($row['value']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(value)%%>', urlencode($urow['value']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(employee)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(employee)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(start)%%>', '<%%creationTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(start)%%>', urlencode('<%%creationTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(stop)%%>', '<%%editingTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(stop)%%>', urlencode('<%%editingTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(horas)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(horas)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(comment)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comment)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(value)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(value)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', 'UNPAID', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode('UNPAID'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Payroll');
	if($selected_id) {
		$jdata = get_joined_record('Payroll', $selected_id);
		if($jdata === false) $jdata = get_defaults('Payroll');
		$rdata = $row;
	}
	$templateCode .= loadView('Payroll-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Payroll_dv
	if(function_exists('Payroll_dv')) {
		$args=array();
		Payroll_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>