<?php

// Data functions (insert, update, delete, form) for table Receivable

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Receivable_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Receivable');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Customer'] = $_REQUEST['Customer'];
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	$data['Phone'] = $_REQUEST['Customer'];
		if($data['Phone'] == empty_lookup_value) { $data['Phone'] = ''; }
	$data['Description'] = $_REQUEST['Description'];
		if($data['Description'] == empty_lookup_value) { $data['Description'] = ''; }
	$data['Interaction'] = br2nl($_REQUEST['Interaction']);
	$data['ExpectedDate'] = intval($_REQUEST['ExpectedDateYear']) . '-' . intval($_REQUEST['ExpectedDateMonth']) . '-' . intval($_REQUEST['ExpectedDateDay']);
	$data['ExpectedDate'] = parseMySQLDate($data['ExpectedDate'], '');
	$data['LastUpdate'] = mysql_datetime($_REQUEST['LastUpdate']);
		if($data['LastUpdate'] == empty_lookup_value) { $data['LastUpdate'] = ''; }
	$data['Status'] = $_REQUEST['Status'];
		if($data['Status'] == empty_lookup_value) { $data['Status'] = ''; }
	$data['Assigned'] = $_REQUEST['Assigned'];
		if($data['Assigned'] == empty_lookup_value) { $data['Assigned'] = ''; }
	$data['Amount'] = $_REQUEST['Amount'];
		if($data['Amount'] == empty_lookup_value) { $data['Amount'] = ''; }
	if($data['Status'] == '') $data['Status'] = "OPEN";

	// hook: Receivable_before_insert
	if(function_exists('Receivable_before_insert')) {
		$args = array();
		if(!Receivable_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Receivable', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Receivable_after_insert
	if(function_exists('Receivable_after_insert')) {
		$res = sql("select * from `Receivable` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Receivable_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Receivable', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Receivable_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Receivable_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Receivable_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Receivable');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Receivable' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Receivable' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Receivable_before_delete
	if(function_exists('Receivable_before_delete')) {
		$args=array();
		if(!Receivable_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Receivable` where `id`='$selected_id'", $eo);

	// hook: Receivable_after_delete
	if(function_exists('Receivable_after_delete')) {
		$args=array();
		Receivable_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Receivable' and pkValue='$selected_id'", $eo);
}

function Receivable_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Receivable');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Receivable' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Receivable' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Customer'] = makeSafe($_REQUEST['Customer']);
		if($data['Customer'] == empty_lookup_value) { $data['Customer'] = ''; }
	$data['Phone'] = makeSafe($_REQUEST['Customer']);
		if($data['Phone'] == empty_lookup_value) { $data['Phone'] = ''; }
	$data['Description'] = makeSafe($_REQUEST['Description']);
		if($data['Description'] == empty_lookup_value) { $data['Description'] = ''; }
	$data['Interaction'] = br2nl(makeSafe($_REQUEST['Interaction']));
	$data['ExpectedDate'] = intval($_REQUEST['ExpectedDateYear']) . '-' . intval($_REQUEST['ExpectedDateMonth']) . '-' . intval($_REQUEST['ExpectedDateDay']);
	$data['ExpectedDate'] = parseMySQLDate($data['ExpectedDate'], '');
	$data['LastUpdate'] = mysql_datetime($_REQUEST['LastUpdate']);
		if($data['LastUpdate'] == empty_lookup_value) { $data['LastUpdate'] = ''; }
	$data['Status'] = makeSafe($_REQUEST['Status']);
		if($data['Status'] == empty_lookup_value) { $data['Status'] = ''; }
	$data['Assigned'] = makeSafe($_REQUEST['Assigned']);
		if($data['Assigned'] == empty_lookup_value) { $data['Assigned'] = ''; }
	$data['Amount'] = makeSafe($_REQUEST['Amount']);
		if($data['Amount'] == empty_lookup_value) { $data['Amount'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Receivable_before_update
	if(function_exists('Receivable_before_update')) {
		$args = array();
		if(!Receivable_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Receivable` set       `Customer`=' . (($data['Customer'] !== '' && $data['Customer'] !== NULL) ? "'{$data['Customer']}'" : 'NULL') . ', `Phone`=' . (($data['Phone'] !== '' && $data['Phone'] !== NULL) ? "'{$data['Phone']}'" : 'NULL') . ', `Description`=' . (($data['Description'] !== '' && $data['Description'] !== NULL) ? "'{$data['Description']}'" : 'NULL') . ', `Interaction`=' . (($data['Interaction'] !== '' && $data['Interaction'] !== NULL) ? "'{$data['Interaction']}'" : 'NULL') . ', `ExpectedDate`=' . (($data['ExpectedDate'] !== '' && $data['ExpectedDate'] !== NULL) ? "'{$data['ExpectedDate']}'" : 'NULL') . ', `LastUpdate`=' . (($data['LastUpdate'] !== '' && $data['LastUpdate'] !== NULL) ? "'{$data['LastUpdate']}'" : 'NULL') . ', `Status`=' . (($data['Status'] !== '' && $data['Status'] !== NULL) ? "'{$data['Status']}'" : 'NULL') . ', `Assigned`=' . (($data['Assigned'] !== '' && $data['Assigned'] !== NULL) ? "'{$data['Assigned']}'" : 'NULL') . ', `Amount`=' . (($data['Amount'] !== '' && $data['Amount'] !== NULL) ? "'{$data['Amount']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Receivable_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Receivable_after_update
	if(function_exists('Receivable_after_update')) {
		$res = sql("SELECT * FROM `Receivable` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Receivable_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Receivable' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Receivable_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Receivable');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Customer = thisOr(undo_magic_quotes($_REQUEST['filterer_Customer']), '');
	$filterer_Assigned = thisOr(undo_magic_quotes($_REQUEST['filterer_Assigned']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Customer
	$combo_Customer = new DataCombo;
	// combobox: ExpectedDate
	$combo_ExpectedDate = new DateCombo;
	$combo_ExpectedDate->DateFormat = "mdy";
	$combo_ExpectedDate->MinYear = 1900;
	$combo_ExpectedDate->MaxYear = 2100;
	$combo_ExpectedDate->DefaultDate = parseMySQLDate('', '');
	$combo_ExpectedDate->MonthNames = $Translation['month names'];
	$combo_ExpectedDate->NamePrefix = 'ExpectedDate';
	// combobox: Status
	$combo_Status = new Combo;
	$combo_Status->ListType = 0;
	$combo_Status->MultipleSeparator = ', ';
	$combo_Status->ListBoxHeight = 10;
	$combo_Status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Receivable.Status.csv')) {
		$Status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Receivable.Status.csv')));
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Status_data)));
		$combo_Status->ListData = $combo_Status->ListItem;
	}else{
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("OPEN;;FOLLOW UP;;CLOSED")));
		$combo_Status->ListData = $combo_Status->ListItem;
	}
	$combo_Status->SelectName = 'Status';
	// combobox: Assigned
	$combo_Assigned = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Receivable' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Receivable' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Receivable` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Receivable_view.php', false);
		}
		$combo_Customer->SelectedData = $row['Customer'];
		$combo_ExpectedDate->DefaultDate = $row['ExpectedDate'];
		$combo_Status->SelectedData = $row['Status'];
		$combo_Assigned->SelectedData = $row['Assigned'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_Customer->SelectedData = $filterer_Customer;
		$combo_Status->SelectedText = ( $_REQUEST['FilterField'][1]=='8' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "OPEN");
		$combo_Assigned->SelectedData = $filterer_Assigned;
	}
	$combo_Customer->HTML = '<span id="Customer-container' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_Customer->MatchText = '<span id="Customer-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Customer" id="Customer' . $rnd1 . '" value="' . html_attr($combo_Customer->SelectedData) . '">';
	$combo_Status->Render();
	$combo_Assigned->HTML = '<span id="Assigned-container' . $rnd1 . '"></span><input type="hidden" name="Assigned" id="Assigned' . $rnd1 . '" value="' . html_attr($combo_Assigned->SelectedData) . '">';
	$combo_Assigned->MatchText = '<span id="Assigned-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Assigned" id="Assigned' . $rnd1 . '" value="' . html_attr($combo_Assigned->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Customer__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Customer'] : $filterer_Customer); ?>"};
		AppGini.current_Assigned__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Assigned'] : $filterer_Assigned); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Customer_reload__RAND__) == 'function') Customer_reload__RAND__();
				if(typeof(Assigned_reload__RAND__) == 'function') Assigned_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Customer_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Customer-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Customer__RAND__.value, t: 'Receivable', f: 'Customer' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Customer"]').val(resp.results[0].id);
							$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


							if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Receivable', f: 'Customer' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Customer__RAND__.value = e.added.id;
				AppGini.current_Customer__RAND__.text = e.added.text;
				$j('[name="Customer"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }


				if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
			});

			if(!$j("#Customer-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Customer__RAND__.value, t: 'Receivable', f: 'Customer' },
					success: function(resp) {
						$j('[name="Customer"]').val(resp.results[0].id);
						$j('[id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

						if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Customer__RAND__.value, t: 'Receivable', f: 'Customer' },
				success: function(resp) {
					$j('[id=Customer-container__RAND__], [id=Customer-container-readonly__RAND__]').html('<span id="Customer-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Customers_view_parent]').hide(); }else{ $j('.btn[id=Customers_view_parent]').show(); }

					if(typeof(Customer_update_autofills__RAND__) == 'function') Customer_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Assigned_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Assigned-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Assigned__RAND__.value, t: 'Receivable', f: 'Assigned' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Assigned"]').val(resp.results[0].id);
							$j('[id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


							if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Receivable', f: 'Assigned' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Assigned__RAND__.value = e.added.id;
				AppGini.current_Assigned__RAND__.text = e.added.text;
				$j('[name="Assigned"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }


				if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
			});

			if(!$j("#Assigned-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Assigned__RAND__.value, t: 'Receivable', f: 'Assigned' },
					success: function(resp) {
						$j('[name="Assigned"]').val(resp.results[0].id);
						$j('[id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

						if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Assigned__RAND__.value, t: 'Receivable', f: 'Assigned' },
				success: function(resp) {
					$j('[id=Assigned-container__RAND__], [id=Assigned-container-readonly__RAND__]').html('<span id="Assigned-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Staff_view_parent]').hide(); }else{ $j('.btn[id=Staff_view_parent]').show(); }

					if(typeof(Assigned_update_autofills__RAND__) == 'function') Assigned_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Receivable_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Receivable_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Receivable details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Receivable_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Receivable_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Receivable_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Customer').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Customer_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Description').replaceWith('<div class=\"form-control-static\" id=\"Description\">' + (jQuery('#Description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Interaction').replaceWith('<div class=\"form-control-static\" id=\"Interaction\">' + (jQuery('#Interaction').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ExpectedDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#ExpectedDateDay, #ExpectedDateMonth, #ExpectedDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#LastUpdate').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"LastUpdate\">' + (jQuery('#LastUpdate').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Status').replaceWith('<div class=\"form-control-static\" id=\"Status\">' + (jQuery('#Status').val() || '') + '</div>'); jQuery('#Status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Assigned').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Assigned_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Amount').replaceWith('<div class=\"form-control-static\" id=\"Amount\">' + (jQuery('#Amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#LastUpdate').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Customer)%%>', $combo_Customer->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Customer)%%>', $combo_Customer->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Customer)%%>', urlencode($combo_Customer->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ExpectedDate)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_ExpectedDate->GetHTML(true) . '</div>' : $combo_ExpectedDate->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ExpectedDate)%%>', $combo_ExpectedDate->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Status)%%>', $combo_Status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Status)%%>', $combo_Status->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Assigned)%%>', $combo_Assigned->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Assigned)%%>', $combo_Assigned->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Assigned)%%>', urlencode($combo_Assigned->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Customer' => array('Customers', 'Customer'), 'Assigned' => array('Staff', 'Assigned'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Customer)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Interaction)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ExpectedDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(LastUpdate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Assigned)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Amount)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', safe_html($urow['Customer']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Customer)%%>', html_attr($row['Customer']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode($urow['Customer']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Description)%%>', safe_html($urow['Description']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Description)%%>', html_attr($row['Description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode($urow['Description']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Interaction)%%>', safe_html($urow['Interaction']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(Interaction)%%>', html_attr($row['Interaction']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Interaction)%%>', urlencode($urow['Interaction']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ExpectedDate)%%>', @date('m/d/Y', @strtotime(html_attr($row['ExpectedDate']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ExpectedDate)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['ExpectedDate'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(LastUpdate)%%>', app_datetime($row['LastUpdate'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LastUpdate)%%>', urlencode(app_datetime($urow['LastUpdate'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', safe_html($urow['Status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', html_attr($row['Status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode($urow['Status']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Assigned)%%>', safe_html($urow['Assigned']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Assigned)%%>', html_attr($row['Assigned']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned)%%>', urlencode($urow['Assigned']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Amount)%%>', safe_html($urow['Amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Amount)%%>', html_attr($row['Amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount)%%>', urlencode($urow['Amount']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Customer)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Customer)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Interaction)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Interaction)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ExpectedDate)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ExpectedDate)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(LastUpdate)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(LastUpdate)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Status)%%>', 'OPEN', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode('OPEN'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Assigned)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Assigned)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tCustomer_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Receivable_autofill.php?rnd1=$rnd1&mfk=Customer&id=' + encodeURIComponent('".addslashes($row['Customer'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Receivable_autofill.php?rnd1=$rnd1&mfk=Customer&id=' + encodeURIComponent(AppGini.current_Customer{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Customer$rnd1').prop('disabled', true); \$j('#CustomerLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#Customer$rnd1').prop('disabled', false); " : "\$j('#Customer$rnd1').prop('disabled', true); ")."\$j('#CustomerLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Customer_caption').length) \$j('#Customer_caption').click(function() { /* */ Customer_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Receivable');
	if($selected_id) {
		$jdata = get_joined_record('Receivable', $selected_id);
		if($jdata === false) $jdata = get_defaults('Receivable');
		$rdata = $row;
	}
	$templateCode .= loadView('Receivable-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Receivable_dv
	if(function_exists('Receivable_dv')) {
		$args=array();
		Receivable_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>