<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Retention.php");
	include("$currDir/Retention_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Retention');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Retention";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Retention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"IF(    CHAR_LENGTH(`Customers1`.`Phone`), CONCAT_WS('',   `Customers1`.`Phone`), '') /* Phone */" => "Phone",
		"IF(    CHAR_LENGTH(`Customers1`.`Email`), CONCAT_WS('',   `Customers1`.`Email`), '') /* Email */" => "Email",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"`Retention`.`Interaction`" => "Interaction",
		"`Retention`.`GIFTPACKAGE`" => "GIFTPACKAGE",
		"IF(    CHAR_LENGTH(`Staff1`.`Employee`), CONCAT_WS('',   `Staff1`.`Employee`), '') /* Assigned */" => "Assigned",
		"`Retention`.`Status`" => "Status",
		"if(`Retention`.`CreateDate`,date_format(`Retention`.`CreateDate`,'%m/%d/%Y %h:%i %p'),'')" => "CreateDate",
		"if(`Retention`.`ResolutionDate`,date_format(`Retention`.`ResolutionDate`,'%m/%d/%Y %h:%i %p'),'')" => "ResolutionDate",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Retention`.`id`',
		2 => '`Customers1`.`Customer`',
		3 => '`Customers1`.`Phone`',
		4 => '`Customers1`.`Email`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`Staff1`.`Employee`',
		9 => 9,
		10 => '`Retention`.`CreateDate`',
		11 => '`Retention`.`ResolutionDate`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Retention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"IF(    CHAR_LENGTH(`Customers1`.`Phone`), CONCAT_WS('',   `Customers1`.`Phone`), '') /* Phone */" => "Phone",
		"IF(    CHAR_LENGTH(`Customers1`.`Email`), CONCAT_WS('',   `Customers1`.`Email`), '') /* Email */" => "Email",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"`Retention`.`Interaction`" => "Interaction",
		"`Retention`.`GIFTPACKAGE`" => "GIFTPACKAGE",
		"IF(    CHAR_LENGTH(`Staff1`.`Employee`), CONCAT_WS('',   `Staff1`.`Employee`), '') /* Assigned */" => "Assigned",
		"`Retention`.`Status`" => "Status",
		"if(`Retention`.`CreateDate`,date_format(`Retention`.`CreateDate`,'%m/%d/%Y %h:%i %p'),'')" => "CreateDate",
		"if(`Retention`.`ResolutionDate`,date_format(`Retention`.`ResolutionDate`,'%m/%d/%Y %h:%i %p'),'')" => "ResolutionDate",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Retention`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"IF(    CHAR_LENGTH(`Customers1`.`Phone`), CONCAT_WS('',   `Customers1`.`Phone`), '') /* Phone */" => "Phone",
		"IF(    CHAR_LENGTH(`Customers1`.`Email`), CONCAT_WS('',   `Customers1`.`Email`), '') /* Email */" => "Email",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"`Retention`.`Interaction`" => "Interaction",
		"`Retention`.`GIFTPACKAGE`" => "Gift Package",
		"IF(    CHAR_LENGTH(`Staff1`.`Employee`), CONCAT_WS('',   `Staff1`.`Employee`), '') /* Assigned */" => "Assigned",
		"`Retention`.`Status`" => "Status",
		"`Retention`.`CreateDate`" => "Open date",
		"`Retention`.`ResolutionDate`" => "Resolution date",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Retention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"IF(    CHAR_LENGTH(`Customers1`.`Phone`), CONCAT_WS('',   `Customers1`.`Phone`), '') /* Phone */" => "Phone",
		"IF(    CHAR_LENGTH(`Customers1`.`Email`), CONCAT_WS('',   `Customers1`.`Email`), '') /* Email */" => "Email",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"`Retention`.`Interaction`" => "Interaction",
		"`Retention`.`GIFTPACKAGE`" => "GIFTPACKAGE",
		"IF(    CHAR_LENGTH(`Staff1`.`Employee`), CONCAT_WS('',   `Staff1`.`Employee`), '') /* Assigned */" => "Assigned",
		"`Retention`.`Status`" => "Status",
		"if(`Retention`.`CreateDate`,date_format(`Retention`.`CreateDate`,'%m/%d/%Y %h:%i %p'),'')" => "CreateDate",
		"if(`Retention`.`ResolutionDate`,date_format(`Retention`.`ResolutionDate`,'%m/%d/%Y %h:%i %p'),'')" => "ResolutionDate",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('Customer' => 'Customer', 'Assigned' => 'Assigned', );

	$x->QueryFrom = "`Retention` LEFT JOIN `Customers` as Customers1 ON `Customers1`.`id`=`Retention`.`Customer` LEFT JOIN `Staff` as Staff1 ON `Staff1`.`id`=`Retention`.`Assigned` LEFT JOIN `Province` as Province1 ON `Province1`.`id`=`Customers1`.`Province` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Retention_view.php";
	$x->RedirectAfterInsert = "Retention_view.php?SelectedID=#ID#";
	$x->TableTitle = "RETENTION";
	$x->TableIcon = "resources/table_icons/Customer.png";
	$x->PrimaryKey = "`Retention`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Customer", "Phone", "Email", "Zone", "Interaction", "Gift Package", "Assigned", "Status", "Open date", "Resolution date");
	$x->ColFieldName = array('Customer', 'Phone', 'Email', 'Zone', 'Interaction', 'GIFTPACKAGE', 'Assigned', 'Status', 'CreateDate', 'ResolutionDate');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Retention_templateTV.html';
	$x->SelectedTemplate = 'templates/Retention_templateTVS.html';
	$x->TemplateDV = 'templates/Retention_templateDV.html';
	$x->TemplateDVP = 'templates/Retention_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Retention`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Retention' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Retention`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Retention' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Retention`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Retention_init
	$render=TRUE;
	if(function_exists('Retention_init')) {
		$args=array();
		$render=Retention_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Retention_header
	$headerCode='';
	if(function_exists('Retention_header')) {
		$args=array();
		$headerCode=Retention_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Retention_footer
	$footerCode='';
	if(function_exists('Retention_footer')) {
		$args=array();
		$footerCode=Retention_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>