<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Staff.php");
	include("$currDir/Staff_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Staff');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Staff";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Staff`.`id`" => "id",
		"`Staff`.`Photo`" => "Photo",
		"`Staff`.`Employee`" => "Employee",
		"if(`Staff`.`Birthdate`,date_format(`Staff`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"`Staff`.`Phone`" => "Phone",
		"`Staff`.`Email`" => "Email",
		"`Staff`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"if(`Staff`.`hireDate`,date_format(`Staff`.`hireDate`,'%m/%d/%Y'),'')" => "hireDate",
		"IF(    CHAR_LENGTH(`Department1`.`Department`), CONCAT_WS('',   `Department1`.`Department`), '') /* Department */" => "Department",
		"IF(    CHAR_LENGTH(`Position1`.`Position`), CONCAT_WS('',   `Position1`.`Position`), '') /* Position */" => "Position",
		"IF(    CHAR_LENGTH(`Supervisor1`.`Supervisor`), CONCAT_WS('',   `Supervisor1`.`Supervisor`), '') /* Supervisor */" => "Supervisor",
		"IF(    CHAR_LENGTH(`Manager1`.`Manager`), CONCAT_WS('',   `Manager1`.`Manager`), '') /* Manager */" => "Manager",
		"IF(    CHAR_LENGTH(`CEO1`.`Chief`), CONCAT_WS('',   `CEO1`.`Chief`), '') /* Director */" => "Director",
		"`Staff`.`Status`" => "Status",
		"`Staff`.`EmergencyContact`" => "EmergencyContact",
		"`Staff`.`EmergencyPhone`" => "EmergencyPhone",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Staff`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Staff`.`Birthdate`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`City1`.`City`',
		9 => '`Province1`.`Province`',
		10 => '`Country1`.`Country`',
		11 => '`Staff`.`hireDate`',
		12 => '`Department1`.`Department`',
		13 => '`Position1`.`Position`',
		14 => '`Supervisor1`.`Supervisor`',
		15 => '`Manager1`.`Manager`',
		16 => '`CEO1`.`Chief`',
		17 => 17,
		18 => 18,
		19 => 19,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Staff`.`id`" => "id",
		"`Staff`.`Photo`" => "Photo",
		"`Staff`.`Employee`" => "Employee",
		"if(`Staff`.`Birthdate`,date_format(`Staff`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"`Staff`.`Phone`" => "Phone",
		"`Staff`.`Email`" => "Email",
		"`Staff`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"if(`Staff`.`hireDate`,date_format(`Staff`.`hireDate`,'%m/%d/%Y'),'')" => "hireDate",
		"IF(    CHAR_LENGTH(`Department1`.`Department`), CONCAT_WS('',   `Department1`.`Department`), '') /* Department */" => "Department",
		"IF(    CHAR_LENGTH(`Position1`.`Position`), CONCAT_WS('',   `Position1`.`Position`), '') /* Position */" => "Position",
		"IF(    CHAR_LENGTH(`Supervisor1`.`Supervisor`), CONCAT_WS('',   `Supervisor1`.`Supervisor`), '') /* Supervisor */" => "Supervisor",
		"IF(    CHAR_LENGTH(`Manager1`.`Manager`), CONCAT_WS('',   `Manager1`.`Manager`), '') /* Manager */" => "Manager",
		"IF(    CHAR_LENGTH(`CEO1`.`Chief`), CONCAT_WS('',   `CEO1`.`Chief`), '') /* Director */" => "Director",
		"`Staff`.`Status`" => "Status",
		"`Staff`.`EmergencyContact`" => "EmergencyContact",
		"`Staff`.`EmergencyPhone`" => "EmergencyPhone",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Staff`.`id`" => "ID",
		"`Staff`.`Employee`" => "Employee",
		"`Staff`.`Birthdate`" => "Birthdate",
		"`Staff`.`Phone`" => "Phone",
		"`Staff`.`Email`" => "Email",
		"`Staff`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"`Staff`.`hireDate`" => "HireDate",
		"IF(    CHAR_LENGTH(`Department1`.`Department`), CONCAT_WS('',   `Department1`.`Department`), '') /* Department */" => "Department",
		"IF(    CHAR_LENGTH(`Position1`.`Position`), CONCAT_WS('',   `Position1`.`Position`), '') /* Position */" => "Position",
		"IF(    CHAR_LENGTH(`Supervisor1`.`Supervisor`), CONCAT_WS('',   `Supervisor1`.`Supervisor`), '') /* Supervisor */" => "Supervisor",
		"IF(    CHAR_LENGTH(`Manager1`.`Manager`), CONCAT_WS('',   `Manager1`.`Manager`), '') /* Manager */" => "Manager",
		"IF(    CHAR_LENGTH(`CEO1`.`Chief`), CONCAT_WS('',   `CEO1`.`Chief`), '') /* Director */" => "Director",
		"`Staff`.`Status`" => "Employment Status",
		"`Staff`.`EmergencyContact`" => "Emergency contact",
		"`Staff`.`EmergencyPhone`" => "Emergency phone",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Staff`.`id`" => "id",
		"`Staff`.`Employee`" => "Employee",
		"if(`Staff`.`Birthdate`,date_format(`Staff`.`Birthdate`,'%m/%d/%Y'),'')" => "Birthdate",
		"`Staff`.`Phone`" => "Phone",
		"`Staff`.`Email`" => "Email",
		"`Staff`.`Address`" => "Address",
		"IF(    CHAR_LENGTH(`City1`.`City`), CONCAT_WS('',   `City1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Province */" => "Province",
		"IF(    CHAR_LENGTH(`Country1`.`Country`), CONCAT_WS('',   `Country1`.`Country`), '') /* Country */" => "Country",
		"if(`Staff`.`hireDate`,date_format(`Staff`.`hireDate`,'%m/%d/%Y'),'')" => "hireDate",
		"IF(    CHAR_LENGTH(`Department1`.`Department`), CONCAT_WS('',   `Department1`.`Department`), '') /* Department */" => "Department",
		"IF(    CHAR_LENGTH(`Position1`.`Position`), CONCAT_WS('',   `Position1`.`Position`), '') /* Position */" => "Position",
		"IF(    CHAR_LENGTH(`Supervisor1`.`Supervisor`), CONCAT_WS('',   `Supervisor1`.`Supervisor`), '') /* Supervisor */" => "Supervisor",
		"IF(    CHAR_LENGTH(`Manager1`.`Manager`), CONCAT_WS('',   `Manager1`.`Manager`), '') /* Manager */" => "Manager",
		"IF(    CHAR_LENGTH(`CEO1`.`Chief`), CONCAT_WS('',   `CEO1`.`Chief`), '') /* Director */" => "Director",
		"`Staff`.`Status`" => "Status",
		"`Staff`.`EmergencyContact`" => "EmergencyContact",
		"`Staff`.`EmergencyPhone`" => "EmergencyPhone",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('City' => 'City', 'Province' => 'Province', 'Country' => 'Country', 'Department' => 'Department', 'Position' => 'Position', 'Supervisor' => 'Supervisor', 'Manager' => 'Manager', 'Director' => 'Director', );

	$x->QueryFrom = "`Staff` LEFT JOIN `City` as City1 ON `City1`.`id`=`Staff`.`City` LEFT JOIN `Province` as Province1 ON `Province1`.`id`=`Staff`.`Province` LEFT JOIN `Country` as Country1 ON `Country1`.`id`=`Staff`.`Country` LEFT JOIN `Department` as Department1 ON `Department1`.`id`=`Staff`.`Department` LEFT JOIN `Position` as Position1 ON `Position1`.`id`=`Staff`.`Position` LEFT JOIN `Supervisor` as Supervisor1 ON `Supervisor1`.`id`=`Staff`.`Supervisor` LEFT JOIN `Manager` as Manager1 ON `Manager1`.`id`=`Staff`.`Manager` LEFT JOIN `CEO` as CEO1 ON `CEO1`.`id`=`Staff`.`Director` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 300;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Staff_view.php";
	$x->RedirectAfterInsert = "Staff_view.php?SelectedID=#ID#";
	$x->TableTitle = "STAFF";
	$x->TableIcon = "resources/table_icons/Staff.png";
	$x->PrimaryKey = "`Staff`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Photo", "Employee", "Birthdate", "Phone", "Email", "Province", "Department", "Position", "Director", "Employment Status");
	$x->ColFieldName = array('Photo', 'Employee', 'Birthdate', 'Phone', 'Email', 'Province', 'Department', 'Position', 'Director', 'Status');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 9, 12, 13, 16, 17);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Staff_templateTV.html';
	$x->SelectedTemplate = 'templates/Staff_templateTVS.html';
	$x->TemplateDV = 'templates/Staff_templateDV.html';
	$x->TemplateDVP = 'templates/Staff_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Staff`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Staff' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Staff`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Staff' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Staff`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Staff_init
	$render=TRUE;
	if(function_exists('Staff_init')) {
		$args=array();
		$render=Staff_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Staff_header
	$headerCode='';
	if(function_exists('Staff_header')) {
		$args=array();
		$headerCode=Staff_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Staff_footer
	$footerCode='';
	if(function_exists('Staff_footer')) {
		$args=array();
		$footerCode=Staff_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>