<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('Status');
	if(!$table_perms[0]) { die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'Tracking':
			if(!$id) {
				?>
				$j('#TrackID<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Dimensions<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#RWeight<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#VWeight<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Total<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `Tracking`.`id` as 'id', IF(    CHAR_LENGTH(`Warehouse1`.`id`), CONCAT_WS('',   `Warehouse1`.`id`), '') as 'WhID', IF(    CHAR_LENGTH(if(`Warehouse1`.`Date`,date_format(`Warehouse1`.`Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Warehouse1`.`Date`,date_format(`Warehouse1`.`Date`,'%m/%d/%Y'),'')), '') as 'Date', IF(    CHAR_LENGTH(`Warehouse1`.`Warehouse`), CONCAT_WS('',   `Warehouse1`.`Warehouse`), '') as 'Warehouse', `Tracking`.`Tracking` as 'Tracking', IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') as 'Customer', `Tracking`.`Dimensions` as 'Dimensions', `Tracking`.`Weight` as 'Weight', `Tracking`.`Volume` as 'Volume', `Tracking`.`Total` as 'Total', IF(    CHAR_LENGTH(`Staff1`.`Employee`), CONCAT_WS('',   `Staff1`.`Employee`), '') as 'Employee', IF(    CHAR_LENGTH(`Warehouse1`.`Freight`), CONCAT_WS('',   `Warehouse1`.`Freight`), '') as 'Freight', `Tracking`.`Status` as 'Status', IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') as 'Zone', if(`Tracking`.`DeliveredDate`,date_format(`Tracking`.`DeliveredDate`,'%m/%d/%Y %h:%i %p'),'') as 'DeliveredDate' FROM `Tracking` LEFT JOIN `Warehouse` as Warehouse1 ON `Warehouse1`.`id`=`Tracking`.`Warehouse` LEFT JOIN `Customers` as Customers1 ON `Customers1`.`id`=`Tracking`.`Customer` LEFT JOIN `Staff` as Staff1 ON `Staff1`.`id`=`Tracking`.`Employee` LEFT JOIN `Province` as Province1 ON `Province1`.`id`=`Customers1`.`Province`  WHERE `Tracking`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#TrackID<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['id']))); ?>&nbsp;');
			$j('#Dimensions<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Dimensions']))); ?>&nbsp;');
			$j('#RWeight<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Weight']))); ?>&nbsp;');
			$j('#VWeight<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Volume']))); ?>&nbsp;');
			$j('#Total<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Total']))); ?>&nbsp;');
			<?php
			break;


	}

?>