<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Subscriptions.php");
	include("$currDir/Subscriptions_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Subscriptions');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Subscriptions";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Subscriptions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"`Subscriptions`.`Vendor`" => "Vendor",
		"`Subscriptions`.`AccountID`" => "AccountID",
		"if(`Subscriptions`.`LastPayment`,date_format(`Subscriptions`.`LastPayment`,'%m/%d/%Y'),'')" => "LastPayment",
		"if(`Subscriptions`.`DueDate`,date_format(`Subscriptions`.`DueDate`,'%m/%d/%Y'),'')" => "DueDate",
		"`Subscriptions`.`Status`" => "Status",
		"`Subscriptions`.`Rate`" => "Rate",
		"`Subscriptions`.`AmountDue`" => "AmountDue",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Subscriptions`.`id`',
		2 => '`Customers1`.`Customer`',
		3 => 3,
		4 => 4,
		5 => '`Subscriptions`.`LastPayment`',
		6 => '`Subscriptions`.`DueDate`',
		7 => 7,
		8 => '`Subscriptions`.`Rate`',
		9 => '`Subscriptions`.`AmountDue`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Subscriptions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"`Subscriptions`.`Vendor`" => "Vendor",
		"`Subscriptions`.`AccountID`" => "AccountID",
		"if(`Subscriptions`.`LastPayment`,date_format(`Subscriptions`.`LastPayment`,'%m/%d/%Y'),'')" => "LastPayment",
		"if(`Subscriptions`.`DueDate`,date_format(`Subscriptions`.`DueDate`,'%m/%d/%Y'),'')" => "DueDate",
		"`Subscriptions`.`Status`" => "Status",
		"`Subscriptions`.`Rate`" => "Rate",
		"`Subscriptions`.`AmountDue`" => "AmountDue",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Subscriptions`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"`Subscriptions`.`Vendor`" => "Vendor",
		"`Subscriptions`.`AccountID`" => "Account ID and Password",
		"`Subscriptions`.`LastPayment`" => "LastPayment",
		"`Subscriptions`.`DueDate`" => "DueDate",
		"`Subscriptions`.`Status`" => "Status",
		"`Subscriptions`.`Rate`" => "Rate",
		"`Subscriptions`.`AmountDue`" => "Amount Due",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Subscriptions`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"`Subscriptions`.`Vendor`" => "Vendor",
		"`Subscriptions`.`AccountID`" => "AccountID",
		"if(`Subscriptions`.`LastPayment`,date_format(`Subscriptions`.`LastPayment`,'%m/%d/%Y'),'')" => "LastPayment",
		"if(`Subscriptions`.`DueDate`,date_format(`Subscriptions`.`DueDate`,'%m/%d/%Y'),'')" => "DueDate",
		"`Subscriptions`.`Status`" => "Status",
		"`Subscriptions`.`Rate`" => "Rate",
		"`Subscriptions`.`AmountDue`" => "AmountDue",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('Customer' => 'Customer', );

	$x->QueryFrom = "`Subscriptions` LEFT JOIN `Customers` as Customers1 ON `Customers1`.`id`=`Subscriptions`.`Customer` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 300;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Subscriptions_view.php";
	$x->RedirectAfterInsert = "Subscriptions_view.php?SelectedID=#ID#";
	$x->TableTitle = "SUSCRIPTIONS";
	$x->TableIcon = "resources/table_icons/Subscriptions.png";
	$x->PrimaryKey = "`Subscriptions`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Customer", "Vendor", "LastPayment", "DueDate", "Status", "Rate", "Amount Due");
	$x->ColFieldName = array('Customer', 'Vendor', 'LastPayment', 'DueDate', 'Status', 'Rate', 'AmountDue');
	$x->ColNumber  = array(2, 3, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Subscriptions_templateTV.html';
	$x->SelectedTemplate = 'templates/Subscriptions_templateTVS.html';
	$x->TemplateDV = 'templates/Subscriptions_templateDV.html';
	$x->TemplateDVP = 'templates/Subscriptions_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Subscriptions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Subscriptions' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Subscriptions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Subscriptions' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Subscriptions`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Subscriptions_init
	$render=TRUE;
	if(function_exists('Subscriptions_init')) {
		$args=array();
		$render=Subscriptions_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])) {
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `Subscriptions`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "select sum(`Subscriptions`.`AmountDue`) from {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="Subscriptions-Customer"></td>';
			$sumRow .= '<td class="Subscriptions-Vendor"></td>';
			$sumRow .= '<td class="Subscriptions-LastPayment"></td>';
			$sumRow .= '<td class="Subscriptions-DueDate"></td>';
			$sumRow .= '<td class="Subscriptions-Status"></td>';
			$sumRow .= '<td class="Subscriptions-Rate"></td>';
			$sumRow .= "<td class=\"Subscriptions-AmountDue text-right\">{$row[0]}</td>";
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: Subscriptions_header
	$headerCode='';
	if(function_exists('Subscriptions_header')) {
		$args=array();
		$headerCode=Subscriptions_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Subscriptions_footer
	$footerCode='';
	if(function_exists('Subscriptions_footer')) {
		$args=array();
		$footerCode=Subscriptions_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>