<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/TrackingCenter.php");
	include("$currDir/TrackingCenter_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('TrackingCenter');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "TrackingCenter";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`TrackingCenter`.`id`" => "id",
		"if(`TrackingCenter`.`Date`,date_format(`TrackingCenter`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Name",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`TrackingCenter`.`Carrier`" => "Carrier",
		"`TrackingCenter`.`Trackingurl`" => "Trackingurl",
		"`TrackingCenter`.`CustStatus`" => "CustStatus",
		"`TrackingCenter`.`TRADEXXstatus`" => "TRADEXXstatus",
		"`TrackingCenter`.`Freight`" => "Freight",
		"`TrackingCenter`.`Comments`" => "Comments",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`TrackingCenter`.`id`',
		2 => '`TrackingCenter`.`Date`',
		3 => '`Customers1`.`Customer`',
		4 => 4,
		5 => '`Tracking1`.`Tracking`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`TrackingCenter`.`id`" => "id",
		"if(`TrackingCenter`.`Date`,date_format(`TrackingCenter`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Name",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`TrackingCenter`.`Carrier`" => "Carrier",
		"`TrackingCenter`.`Trackingurl`" => "Trackingurl",
		"`TrackingCenter`.`CustStatus`" => "CustStatus",
		"`TrackingCenter`.`TRADEXXstatus`" => "TRADEXXstatus",
		"`TrackingCenter`.`Freight`" => "Freight",
		"`TrackingCenter`.`Comments`" => "Comments",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`TrackingCenter`.`id`" => "ID",
		"`TrackingCenter`.`Date`" => "Date",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Customer",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`TrackingCenter`.`Carrier`" => "Carrier",
		"`TrackingCenter`.`Trackingurl`" => "Tracking URL (optional)",
		"`TrackingCenter`.`CustStatus`" => "Customer Status",
		"`TrackingCenter`.`TRADEXXstatus`" => "Tradexx status",
		"`TrackingCenter`.`Freight`" => "Shipping type",
		"`TrackingCenter`.`Comments`" => "Comments",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`TrackingCenter`.`id`" => "id",
		"if(`TrackingCenter`.`Date`,date_format(`TrackingCenter`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Customers1`.`Customer`), CONCAT_WS('',   `Customers1`.`Customer`), '') /* Customer */" => "Name",
		"IF(    CHAR_LENGTH(`Province1`.`Province`), CONCAT_WS('',   `Province1`.`Province`), '') /* Zone */" => "Zone",
		"IF(    CHAR_LENGTH(`Tracking1`.`Tracking`), CONCAT_WS('',   `Tracking1`.`Tracking`), '') /* Tracking */" => "Tracking",
		"`TrackingCenter`.`Carrier`" => "Carrier",
		"`TrackingCenter`.`Trackingurl`" => "Trackingurl",
		"`TrackingCenter`.`CustStatus`" => "CustStatus",
		"`TrackingCenter`.`TRADEXXstatus`" => "TRADEXXstatus",
		"`TrackingCenter`.`Freight`" => "Freight",
		"`TrackingCenter`.`Comments`" => "Comments",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('Name' => 'Customer', 'Tracking' => 'Tracking', );

	$x->QueryFrom = "`TrackingCenter` LEFT JOIN `Customers` as Customers1 ON `Customers1`.`id`=`TrackingCenter`.`Name` LEFT JOIN `Tracking` as Tracking1 ON `Tracking1`.`id`=`TrackingCenter`.`Tracking` LEFT JOIN `Province` as Province1 ON `Province1`.`id`=`Customers1`.`Province` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 300;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "TrackingCenter_view.php";
	$x->RedirectAfterInsert = "TrackingCenter_view.php?SelectedID=#ID#";
	$x->TableTitle = "TRACKING CENTER";
	$x->TableIcon = "resources/table_icons/Tracking center 1.png";
	$x->PrimaryKey = "`TrackingCenter`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Date", "Customer", "Zone", "Tracking", "Carrier", "Tracking URL (optional)", "Customer Status", "Tradexx status", "Shipping type", "Comments");
	$x->ColFieldName = array('Date', 'Name', 'Zone', 'Tracking', 'Carrier', 'Trackingurl', 'CustStatus', 'TRADEXXstatus', 'Freight', 'Comments');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/TrackingCenter_templateTV.html';
	$x->SelectedTemplate = 'templates/TrackingCenter_templateTVS.html';
	$x->TemplateDV = 'templates/TrackingCenter_templateDV.html';
	$x->TemplateDVP = 'templates/TrackingCenter_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `TrackingCenter`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='TrackingCenter' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `TrackingCenter`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='TrackingCenter' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`TrackingCenter`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: TrackingCenter_init
	$render=TRUE;
	if(function_exists('TrackingCenter_init')) {
		$args=array();
		$render=TrackingCenter_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: TrackingCenter_header
	$headerCode='';
	if(function_exists('TrackingCenter_header')) {
		$args=array();
		$headerCode=TrackingCenter_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: TrackingCenter_footer
	$footerCode='';
	if(function_exists('TrackingCenter_footer')) {
		$args=array();
		$footerCode=TrackingCenter_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>